#!/bin/sh
# Chhatri n8n entrypoint (SPEC §14.5, §23; decision B1).
#
# Imports every workflow in $CHHATRI_WORKFLOW_DIR (generated by scripts/n8n_workflows.py; ids are fixed,
# so a restart re-imports in place), publishes (activates) each one, then starts n8n through the image's
# own entrypoint. The workflows read CHHATRI_INTERNAL_SECRET and CHHATRI_PUBLIC_URL from the environment
# (N8N_BLOCK_ENV_ACCESS_IN_NODE=false), so both must be set; start-up fails fast otherwise.
set -eu

WORKFLOW_DIR="${CHHATRI_WORKFLOW_DIR:-/chhatri/workflows}"
N8N_START="${CHHATRI_N8N_START:-/docker-entrypoint.sh}"  # the image's own entrypoint

log() {
    echo "[chhatri-n8n] $*"
}

fail() {
    echo "[chhatri-n8n] ERROR: $*" >&2
    exit 1
}

[ -n "${CHHATRI_INTERNAL_SECRET:-}" ] || fail "CHHATRI_INTERNAL_SECRET is not set"
[ -n "${CHHATRI_PUBLIC_URL:-}" ] || fail "CHHATRI_PUBLIC_URL is not set"
[ -d "$WORKFLOW_DIR" ] || fail "workflow directory $WORKFLOW_DIR is missing"

found=0
for file in "$WORKFLOW_DIR"/chhatri-*.json; do
    [ -f "$file" ] || continue
    found=$((found + 1))
done
[ "$found" -gt 0 ] || fail "no chhatri-*.json workflows in $WORKFLOW_DIR"

log "importing $found workflows from $WORKFLOW_DIR"
n8n import:workflow --separate --input="$WORKFLOW_DIR" || fail "workflow import failed"

for file in "$WORKFLOW_DIR"/chhatri-*.json; do
    id="$(basename "$file" .json)"
    log "publishing $id"
    n8n publish:workflow --id="$id" || fail "could not publish $id"
done

log "starting n8n; callbacks go to $CHHATRI_PUBLIC_URL/internal/workflows/{step}"
exec "$N8N_START" start
