"""What the HTTP layer needs from the integration core (SPEC §24.6), as structural types.

The API depends only on these protocols, which name exactly the SPEC §24.6 / §24.3 / §24.4 members
it calls. ``chhatri.replay.state.AppState`` and its ``Runtime`` satisfy them; tests use fakes.
Keeping the replay import out of module import time lets the API start (and report preflight)
even while artefacts are missing.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import date, datetime
from pathlib import Path
from typing import Any, Protocol

from chhatri.config import Settings
from chhatri.domain.enums import CaseStatus
from chhatri.domain.models import (
    AuditEntry,
    Case,
    CoverQuote,
    Decision,
    Merchant,
    Message,
    Payout,
    PremiumPayment,
    Zone,
)
from chhatri.events import EventBus
from chhatri.integrations.base import (
    DeliveryReceipt,
    InboundMedia,
    IntegrationStatus,
    OutboundMessage,
    RainSeries,
)

__all__ = ["AppStatePort", "RuntimePort", "StaticPort"]


class CityPort(Protocol):
    @property
    def merchants(self) -> tuple[Merchant, ...]: ...
    @property
    def zones(self) -> tuple[Zone, ...]: ...
    def merchant(self, merchant_id: str) -> Merchant: ...


class StaticPort(Protocol):
    @property
    def settings(self) -> Settings: ...
    @property
    def rules(self) -> Any: ...
    @property
    def data_dir(self) -> Path: ...
    @property
    def city(self) -> CityPort: ...
    @property
    def zones_geojson(self) -> dict[str, Any]: ...
    @property
    def hexes_geojson(self) -> dict[str, Any]: ...
    @property
    def backtest_report(self) -> dict[str, Any] | None: ...


class ScenarioPort(Protocol):
    @property
    def name(self) -> str: ...
    @property
    def demo_merchant_id(self) -> str: ...
    @property
    def slip_sample(self) -> str | None: ...


class ClockPort(Protocol):
    def now(self) -> datetime: ...


class IdsPort(Protocol):
    def next(self, kind: str) -> str: ...


class StorePort(Protocol):
    def case(self, case_id: str) -> Case: ...
    def cases(self, status: CaseStatus | None = None) -> tuple[Case, ...]: ...
    def decision(self, decision_id: str) -> Decision: ...
    def payouts(self, *, zone_id: str | None = None, day: date | None = None) -> tuple[Payout, ...]: ...
    def messages(self, merchant_id: str) -> tuple[Message, ...]: ...
    def media(self, media_id: str) -> tuple[bytes, str]: ...


class AuditPort(Protocol):
    def entries(self, *, after: int = 0, limit: int = 200) -> tuple[AuditEntry, ...]: ...
    def verify(self) -> dict[str, Any]: ...
    def __len__(self) -> int: ...


class EnginePort(Protocol):
    async def play(self, speed: float | None = None) -> None: ...
    async def pause(self) -> None: ...
    async def step(self, minutes: int) -> None: ...
    async def seek(self, hhmm: str) -> None: ...


class OrchestratorPort(Protocol):
    async def handle_callback(
        self, run_id: str, workflow: str, step: str, payload: Mapping[str, Any]
    ) -> dict[str, Any]: ...
    async def officer_decide(
        self, case_id: str, *, approve: bool, officer_id: str, note: str
    ) -> Decision: ...
    async def paytm_paid(self, link_id: str, txn_id: str | None) -> PremiumPayment: ...
    async def quote_cover(self, merchant_id: str) -> tuple[CoverQuote, PremiumPayment | None]: ...


class ConversationPort(Protocol):
    async def handle_text(self, merchant_id: str, text: str) -> tuple[Message, ...]: ...
    async def handle_voice(
        self, merchant_id: str, audio: bytes, mime: str, *, transcript_hint: str | None = None
    ) -> tuple[Message, ...]: ...
    async def handle_image(
        self, merchant_id: str, image: bytes, mime: str, media_id: str
    ) -> tuple[Message, ...]: ...


class ChannelPort(Protocol):
    async def send(self, message: OutboundMessage) -> DeliveryReceipt: ...
    async def download_media(self, media_id: str) -> InboundMedia: ...


class WeatherPort(Protocol):
    async def hourly_rain(self, latitude: float, longitude: float, start: date, end: date) -> RainSeries: ...


class IntegrationsPort(Protocol):
    @property
    def statuses(self) -> Sequence[IntegrationStatus]: ...
    @property
    def channel(self) -> ChannelPort: ...
    @property
    def weather(self) -> WeatherPort: ...


class RuntimePort(Protocol):
    @property
    def scenario(self) -> ScenarioPort: ...
    @property
    def clock(self) -> ClockPort: ...
    @property
    def ids(self) -> IdsPort: ...
    @property
    def store(self) -> StorePort: ...
    @property
    def audit(self) -> AuditPort: ...
    @property
    def engine(self) -> EnginePort: ...
    @property
    def orchestrator(self) -> OrchestratorPort: ...
    @property
    def conversation(self) -> ConversationPort: ...
    @property
    def integrations(self) -> IntegrationsPort: ...


class AppStatePort(Protocol):
    @property
    def static(self) -> StaticPort: ...
    @property
    def bus(self) -> EventBus: ...
    @property
    def runtime(self) -> RuntimePort: ...
    async def load(self, scenario: str) -> RuntimePort: ...
    async def shutdown(self) -> None: ...
    def preflight(self) -> list[dict[str, Any]]: ...
