/**
 * English strings of the mini-app: the source of the key list. Keys are the dotted lower-case keys of the copy deck
 * (docs/03-design/copy-deck.md); a line quoted from the deck keeps its wording. Lines marked "proposed" are new
 * and need a native review, like every proposed line of the deck. Screens add their own section here, and the
 * same keys go into hi.ts (a missing key fails the typecheck and copy.test.ts). Rule numbers never appear in a
 * string: they arrive through {placeholders} (useRules).
 */
export const en = {
  // Shell and settings (copy deck 2.1)
  'nav.home': 'Home',
  'nav.claims': 'Claims',
  'nav.help': 'Help',
  'app.name': 'Chhatri',
  'app.tagline': 'Chhatri in Paytm for Business',
  'app.clock': 'Demo date and time: {time}',
  'app.fullscreen': 'Open full screen',
  // The demo clock sheet of the standalone route (screens-and-flows 8, proposed)
  'clock.sheet.title': 'Demo date and time',
  'clock.sheet.note': 'Move the demo clock. The replay is made up.',
  'clock.sheet.play': 'Play',
  'clock.sheet.pause': 'Pause',
  'clock.sheet.start': 'Back to the start',
  'clock.chapter.alert': 'Alert',
  'clock.chapter.trigger': 'Trigger',
  'clock.chapter.paid': 'Paid',
  'clock.chapter.instalment': 'Instalment',
  'clock.chapter.checkin': 'Check-in',
  'clock.chapter.cover': 'Cover asked',
  'lang.label': 'Language',
  'lang.hi': 'हिंदी',
  'lang.en': 'English',
  'lang.mr': 'मराठी',
  'lang.fallback_note': 'Some text is shown in Hindi.',
  'settings.title': 'Settings',
  'ask.title': 'Ask Chhatri',

  // Screen titles (copy deck 2.2 to 4)
  'home.title': 'Your cover',
  'explain.title': 'What am I covered for?',
  'buy.title': 'Get cover',
  'tracker.title': 'Your claims',
  'why.title': 'Why did I get this amount?',
  'receipt.title': 'Your payout receipt',

  // States (copy deck 15)
  'empty.claims':
    "No claims yet. If your area's sales fall during a weather alert, Chhatri starts a claim for you. If your shop has no sales for a full day, Chhatri will ask if you are okay.",
  'empty.cover': 'You have no cover yet.',
  'empty.receipt': 'No receipt yet. A receipt appears after a payout is credited.',
  'error.title': 'Could not load this',
  'error.generic': 'Something went wrong. Try again.',
  'error.retry': 'Try again',
  'error.code': 'Error code: {code}',
  'error.network': 'We cannot connect right now. Check your internet and try again.',
  'error.timeout': 'This is taking too long. Please try again in a moment.',
  'error.not_found': 'We could not find this. It may have been removed, or the link is wrong.',
  'offline.banner': 'Offline. Showing data from {time}.',
  'offline.blocked': 'This needs the internet. Please try again when you are online.',
  'offline.static': 'This is the static demo. It runs in your browser with made-up data. Nothing is sent anywhere.',
  'explain.btn.got_it': 'Got it',
  'sim.banner': 'SIMULATED. This is demo data. No real money, message or payment moves.',

  // Shell labels (proposed)
  'app.frame_label': 'Chhatri app, simulated',
  'app.tabs': 'Main tabs',
  'app.nba': 'Next step',
  'app.back': 'Back',
  'app.unknown_merchant': 'Unknown merchant',
  'state.loading': 'Loading',

  // Home and cover card (copy deck 2.2)
  'home.greeting': 'Hello, {name} ji',
  'cover.status.pending_payment': 'Waiting for your first payment',
  'cover.status.waiting': 'Starts on {date}',
  'cover.status.active': 'Active',
  'cover.status.active_unpaid': 'Active, premium not paid for the coming days',
  'cover.status.lapsed': 'Stopped',
  'cover.status.cancelled': 'Cancelled',
  'home.row.zone': 'Your area',
  'home.row.premium_per_day': 'Premium a day',
  'home.row.paid_through': 'Paid up to',
  'home.row.starts_on': 'Cover starts',
  'home.row.instalment': 'Loan instalment a day',
  'home.used': 'Used in the last {window_days} days: {used} of {limit}',
  'home.expected': 'Expected sales today',
  'home.latest': 'Your latest claim',
  'home.btn.coverage': 'What am I covered for?',
  'home.btn.buy': 'Get cover',
  'home.btn.claims': 'See my claims',
  'home.btn.ask': 'Ask Chhatri',
  'home.alert.banner': 'Alert {alert_id} · {valid_from} to {valid_to}',
  'home.alert.covered': "A weather alert is on for your area. Chhatri is watching your area's sales. You do not need to do anything.",
  'home.alert.not_covered': 'A weather alert is on for your area. New cover starts after the waiting period, so it will not apply to this alert.',
  'alert.id': 'Alert {alert_id}',

  // Coverage explainer (copy deck 2.3)
  'explain.numbers.title': 'Your cover in numbers',
  'explain.num.share': "Chhatri's share of lost sales",
  'explain.num.area_cap': 'Daily limit, rain',
  'explain.num.personal_cap': 'Daily limit, hospital cash',
  'explain.num.annual': 'Yearly limit',
  'explain.num.waiting': 'Waiting period',
  'explain.num.lookahead': 'Alerts checked this far ahead',
  'explain.num.first_days': 'First payment covers',
  'explain.c2.title': 'Rain and lost sales',
  'explain.c2.body':
    "When a weather alert is on, your area's sales stay below {floor_pct}% of the usual level for {hours} hours in a row, and the fall is bigger than an ordinary slow day, Chhatri pays {share_pct}% of your shop's lost sales, worked out from your usual day and the area's drop. The most is {area_cap} a day. You do not need to file anything.",
  'explain.c2.example':
    "A tea stall usually sells ₹4,380 on a Tuesday. One rainy Tuesday the area's sales fell 63%. Half of the lost sales is ₹1,379.70, which rounds to ₹1,380, so the stall was paid ₹1,380.",
  'explain.c3.title': 'Hospital cash',
  'explain.c3.body':
    'If your shop has no sales for a full day, Chhatri asks if you are okay. If you are in hospital, send one photo of the hospital slip. When the slip checks out, Chhatri pays {share_pct}% of your usual day, up to {personal_cap} a day, for up to {max_auto_days} days. A person looks at anything longer.',
  'explain.c3.example':
    'A shop usually sells ₹4,300 on a Wednesday. The owner was in hospital and the shop had no sales that day. Half of ₹4,300 is ₹2,150, but the limit is ₹1,500 a day, so ₹1,500 was paid for that day.',
  'explain.c4.title': 'How much Chhatri pays',
  'explain.c4.body':
    'Chhatri pays {share_pct}% of the sales you lost. The most for one day is {area_cap} for rain and {personal_cap} for hospital cash. Hospital cash is paid without a review for up to {max_auto_days} days. All payouts together stop at {annual_limit} in any {window_days} days.',
  'explain.c5.title': 'When cover starts',
  'explain.c5.body':
    'A new cover starts {waiting_days} days after you ask. If an alert for your area is on, or was issued and starts within {lookahead_hours} hours, you cannot start cover right away. You can still buy cover for later. Cover bought after an alert was issued never pays for that alert.',
  'explain.c5.example': 'Ramesh asks on Monday 18 August at 18:00. His cover starts on 25 August.',
  'explain.c6.title': 'Premium and prepaid days',
  'explain.c6.body':
    "The first payment covers {first_days} days. After that, the evening settlement takes the next day's premium, with your standing consent. Cover works on the days whose premium was paid in advance.",
  'explain.c6.example': 'In the demo, Zone 3 costs ₹14.16 a day, so 30 days is ₹424.80. The real price is not decided yet.',
  'explain.c7.title': 'When a claim is not paid',
  'explain.c7.body':
    'A claim is not paid when a check that must pass does not pass. The list below gives the reasons Chhatri gives. Anything the system is unsure about goes to a person. That is not a refusal.',
  'explain.c10.title': 'Your loan instalment',
  'explain.c10.body': 'After a payout, Chhatri asks your lender to pause your next instalment. The lender decides, not Chhatri.',
  'explain.example.title': 'Example',
  'explain.example.sim': 'Example from a simulated replay',
  'explain.price.covered': 'Your price: {per_day} a day.',
  'explain.price.uncovered': 'You see your price when you tap Get cover.',
  'explain.price.prototype': 'Prototype price. The real price is not decided yet.',
  'explain.no_forms': 'Rain claims need no forms. Hospital cash needs one photo of the slip.',
  'explain.rules_note': 'These are the demo rules ({rules_version}). They are illustrative. A partner insurer would set the real terms.',
  'explain.terms_hint': 'Tap an underlined word to see what it means.',
  'reason.cover_in_force': "Your cover wasn't in force on that day.",
  'reason.premium_prepaid': "The premium for that day hadn't been paid in advance.",
  'reason.silence_verified': "Our records don't show your shop closed for that whole day.",
  'reason.not_already_paid': 'That day has already been paid.',
  'reason.within_annual_limit': 'It would go over the yearly limit.',
  'reason.cover_before_alert': 'The cover was bought after the alert was issued.',
  'reason.alert_active': 'There was no weather alert for your area at that time.',
  'reason.index_quorum': 'Too few shops in your area to measure the drop.',
  'reason.below_floor': "Your area's sales didn't fall below the payout level.",
  'reason.below_model_range': "Your area's sales stayed within their usual range.",

  // Get cover (copy deck 2.4, proposed lines marked)
  'buy.intro': 'New cover always starts {waiting_days} days after you ask.',
  'buy.check': 'Check price and start date',
  'buy.outcome.ok': 'Cover starts on {date}',
  'buy.outcome.blocked': 'Blocked for now. Cover starts on {date}.',
  'buy.row.starts': 'Cover starts',
  'buy.row.per_day': 'Premium a day',
  'buy.row.first_payment': 'First payment ({first_days} days)',
  'buy.blocked_note': 'Cover bought after an alert was issued does not pay for that alert. You can still buy cover for later.',
  'buy.consent.notice': 'Chhatri uses your sales data to decide claims and set your premium.',
  'buy.consent.text': "Before you pay: Chhatri uses your sales data to decide claims and set your premium. After the first payment, Chhatri takes the next day's premium from your daily settlement. Chhatri reads a hospital slip when you send one, for that claim alone. You can turn each of these off in the app under Help, My data and consent. This is a prototype with simulated data.",
  'buy.consent.version': 'Notice version {version}',
  'buy.consent.box.SALES_DATA_FOR_CLAIM': 'I agree: Chhatri may use my sales data to decide claims and set my premium.',
  'buy.consent.box.SETTLEMENT_DEDUCTION': "I agree: after the first payment, Chhatri may take the next day's premium from my daily settlement.",
  'buy.consent.box.SLIP_DATA_FOR_HOSPITAL_CLAIM': 'I agree: Chhatri may read a hospital slip when I send one.',
  'buy.consent.tag.required': 'Needed for cover',
  'buy.consent.tag.optional': 'Optional',
  'buy.consent.hint': 'Tick the two boxes marked Needed for cover to continue.',
  'buy.consent.error': 'The notice changed. Please read it again.',
  'buy.pay': 'Pay with Paytm',
  'buy.simulate': 'Simulate payment',
  'buy.pending': 'Waiting for your payment. This page updates when it arrives.',
  'buy.link.simulated': 'SIMULATED payment link. No real money moves.',
  'buy.paid': 'Payment received.',
  'buy.link_label': 'Payment link',
  'buy.link_unavailable': "The payment link couldn't be created right now. Please ask again in a little while.",
  'buy.needs_presenter': "This demo action needs the presenter's session.",
  'error.pay_failed': 'The payment did not go through. No money was taken. You can try again.',

  // Help, Settings and Language (copy deck 2.1, 5.2; proposed lines marked)
  'help.about.title': 'About this prototype',
  'help.about.text':
    'Prototype. Anil Jadhav and every merchant here are synthetic. Anything marked SIMULATED is not real: sales, alerts, KYC, payouts, lender, Soundbox, WhatsApp and the Paytm link.',
  'origin.LIVE.hint': 'A real connection supplied this.',
  'origin.SIMULATED.hint': 'Demo data. No real money, message or payment moves.',
  'mode.FALLBACK.hint': 'A backup is in use because the usual service was not available.',
  'help.glossary.title': 'Insurance words in plain language',
  'help.dispute.hint': 'If an amount looks wrong, open the claim and tap This is wrong.',
  'lang.preview': 'Preview',
  'lang.native_hint': 'Each language is shown in its own script.',

  // Jargon lens (copy deck 7)
  'lens.title': 'What does this word mean?',
  'lens.plain': 'In plain words',
  'lens.example': 'Example',
  'lens.close': 'Close',
  'lens.footer': 'This explains the word in plain language. The policy wording has the exact terms.',
  'jargon.waiting_period.term': 'Waiting period',
  'jargon.waiting_period.what': 'A new cover starts {waiting_days} days after you ask. Until then it does not pay.',
  'jargon.waiting_period.example': 'Ramesh asks on Monday 18 August. His cover starts on 25 August.',
  'jargon.alert.term': 'Weather alert',
  'jargon.alert.what': 'A weather warning for your area. Cover bought after an alert is issued does not pay for that alert.',
  'jargon.alert.example': 'Alert A-20250818-01 was issued on Monday 18 August at 17:30 for the next day.',
  'jargon.expected_day.term': 'Your usual day',
  'jargon.expected_day.what': 'What Chhatri expects your shop to sell on this day of the week, worked out from your past sales.',
  'jargon.expected_day.example': "Anil's usual Tuesday: ₹4,380.",
  'jargon.area_drop.term': 'Area drop',
  'jargon.area_drop.what': 'How far sales across the shops in your area fell below what was expected, in per cent.',
  'jargon.area_drop.example': 'On 19 August Zone 7 was at 37% of expected, a 63% drop.',
  'jargon.payout_share.term': "Chhatri's share",
  'jargon.payout_share.what': 'Chhatri pays {share_pct}% of the sales you lost.',
  'jargon.payout_share.example': '½ × ₹4,380 × 63% = ₹1,380: half, times your usual day, times the area drop.',
  'jargon.daily_cap.term': 'Daily limit',
  'jargon.daily_cap.what': 'The most Chhatri pays for one day: {area_cap} for rain and {personal_cap} for hospital cash.',
  'jargon.daily_cap.example': 'Half of a ₹4,300 day is ₹2,150, but the hospital limit is ₹1,500 a day, so ₹1,500 is paid.',
  'jargon.annual_limit.term': 'Yearly limit',
  'jargon.annual_limit.what': 'The most Chhatri pays you in any {window_days} days: {annual_limit}.',
  'jargon.annual_limit.example': 'A claim that would take you over the limit is not paid.',
  'jargon.premium.term': 'Premium',
  'jargon.premium.what': 'The small amount you pay each day for cover.',
  'jargon.premium.example': 'In the demo, Zone 3 costs ₹14.16 a day, so 30 days is ₹424.80. The real price is not decided.',
  'jargon.prepaid_through.term': 'Paid up to',
  'jargon.prepaid_through.what': 'Cover works on days whose premium was paid in advance. This is the last paid day.',
  'jargon.prepaid_through.example': "Ramesh's ₹424.80 pays for 30 days, 25 August to 23 September.",
  'jargon.settlement.term': 'Settlement',
  'jargon.settlement.what': 'The transfer of your Paytm sales to your bank account.',
  'jargon.settlement.example': "Anil's ₹1,380 arrived with the settlement at 17:04 (SIMULATED).",
  'jargon.edi_holiday.term': 'Instalment holiday (EDI)',
  'jargon.edi_holiday.what': "If you repay your loan every day (EDI), your lender can pause one day's instalment. The lender decides, not Chhatri.",
  'jargon.edi_holiday.example': "Anil's ₹600 instalment: Chhatri asks, the lender answers.",
  'jargon.kyc.term': 'KYC',
  'jargon.kyc.what': 'The identity details Paytm already holds about you, such as your name.',
  'jargon.kyc.example': 'The name on a hospital slip is compared with your KYC name. A score of {name_match_min} or more matches.',
  'jargon.referred.term': 'With a claims officer',
  'jargon.referred.what': 'A person at Chhatri decides. It is not a refusal. You hear back within {sla_hours} hours.',
  'jargon.referred.example': 'The name "Sunil Pawar" on the slip did not match KYC, so case C-2291 went to an officer.',
  'jargon.audit_fingerprint.term': 'Audit code',
  'jargon.audit_fingerprint.what':
    "Each decision is written to a chained log. Changing an old line would break the chain. This code identifies this decision's line.",
  'jargon.audit_fingerprint.example': '"Check the log" tells you whether the whole log is unbroken.',
  'jargon.rules_version.term': 'Rules version',
  'jargon.rules_version.what': 'The version of the rule book used for this decision.',
  'jargon.rules_version.example': 'For example: {rules_version}.',

  // Next best action: a sentence and a button for each rule (copy deck 8.1, wave 1)
  'nba.get_cover_from_coverage': 'Ready for cover? Check your price and start date.',
  'nba.get_cover_from_coverage.btn': 'Get cover',
  'nba.see_claims': 'See what Chhatri has done for you.',
  'nba.see_claims.btn': 'See my claims',
  'nba.home_from_coverage': 'That is all about cover.',
  'nba.home_from_coverage.btn': 'Back to Home',
  'nba.check_price': 'See your price and start date first.',
  'nba.check_price.btn': 'Check price and start date',
  'nba.pay': 'Pay the first payment to start your cover.',
  'nba.pay.btn': 'Pay with Paytm',
  'nba.home_after_paid': 'Payment received.',
  'nba.home_after_paid.btn': 'Back to Home',
  'nba.home_when_covered': 'You already have cover.',
  'nba.home_when_covered.btn': 'Back to Home',
  'nba.open_latest': 'Open your latest claim to see each step.',
  'nba.open_latest.btn': 'Open the latest claim',
  'nba.see_coverage_empty': 'No claims yet. See what is covered.',
  'nba.see_coverage_empty.btn': 'See what is covered',
  'nba.wait_for_officer': 'A claims officer is looking at this. You will hear back within {sla_hours} hours.',
  'nba.wait_for_officer.btn': 'Back to claims',
  'nba.see_why': 'Your payout of {amount} was credited. See how it was worked out.',
  'nba.see_why.btn': 'Why this amount?',
  'nba.back_to_claims': 'That is all for this claim.',
  'nba.back_to_claims.btn': 'Back to claims',
  'nba.see_receipt': 'Keep a receipt of this decision.',
  'nba.see_receipt.btn': 'See the receipt',
  'nba.disagree': 'Do you disagree? Tell us.',
  'nba.disagree.btn': 'This is wrong',
  'nba.home_after_language': 'Language saved.',
  'nba.home_after_language.btn': 'Back to Home',
  'nba.see_dispute_case': 'Your case is with a claims officer. You will hear back within {sla_hours} hours.',
  'nba.see_dispute_case.btn': 'See my case',
  'nba.see_referred_claim': 'A claims officer is checking your claim.',
  'nba.see_referred_claim.btn': 'See my claim',
  'nba.see_coverage_waiting': 'Your cover starts on {starts_on}.',
  'nba.see_coverage_waiting.btn': 'See what is covered',
  'nba.get_cover': 'You have no cover yet.',
  'nba.get_cover.btn': 'Get cover',
  'nba.see_premium': 'Your premium is not paid for the coming days. See how it works.',
  'nba.see_premium.btn': 'See how it works',
  'nba.alert_notice': "There is an alert for your area. If your area's sales fall, Chhatri checks the numbers on its own.",
  'nba.alert_notice.btn': 'See what is covered',
  'nba.see_coverage': 'See what you are covered for.',
  'nba.see_coverage.btn': 'See what is covered',
  'nba.tick_consent': 'Tick the boxes marked Needed for cover to go on.',
  'nba.tick_consent.btn': 'Go to the boxes',
  'nba.send_slip': 'Send one photo of your hospital slip.',
  'nba.send_slip.btn': 'Send the slip photo',
  'nba.ask': 'Have a question? Ask Chhatri.',
  'nba.ask.btn': 'Ask Chhatri',

  // Labels shared with the claim screens (copy deck 3.1)
  'tracker.kind.area': 'Rain and lost sales',
  'tracker.kind.personal': 'Hospital cash',
  'tracker.kind.dispute': 'Question about a payout',
  'tracker.state.now': 'In progress',
  'claim.status.approved_pending': 'Approved. Credit is on its way.',
  'claim.status.paid': 'Paid',
  'claim.status.referred': 'With a claims officer',
  'claim.status.declined': 'Not paid',
  'claim.status.waiting_slip': 'Waiting for your slip',
  'claim.status.question_open': 'Question open',
  'claim.status.question_closed': 'Question closed. Amount unchanged.',

  // Claims, tracker, why and receipt (card 3.10): copy deck sections 3, 4, 5, 6, 13.1, 15.4. A line marked "proposed" is new and needs the native review.
  'tracker.step.detected': 'Detected',
  'tracker.step.checked': 'Checked',
  'tracker.step.decided': 'Decided',
  'tracker.step.paid': 'Paid',
  'tracker.step.edi': 'Instalment holiday (EDI)',
  'tracker.state.done': 'Done',
  'tracker.state.waiting': 'Waiting',
  'tracker.state.na': 'Not needed',
  'tracker.state.stopped': 'Stopped here',
  'tracker.clock.left': '{hours} hours left',
  'tracker.clock.due': 'Reply due by {time}',
  'tracker.clock.overdue': 'Past the time limit',
  'tracker.btn.receipt': 'See receipt',
  'tracker.btn.wrong': 'This is wrong',
  'tracker.btn.why': 'Why this amount?',
  'tracker.next.referred': 'Next: a person decides. You will hear back within {sla_hours} hours.',
  'tracker.next.after_decided': 'Next: the money is credited with the settlement.',
  'tracker.next.after_paid': 'Next: if you have a loan, your lender decides about the instalment.',
  'tracker.next.done': 'All steps are done. Your receipt is ready.',
  'tracker.next.declined': 'You can ask for the reason or talk to our team.',
  'why.numbers': 'Your numbers',
  'why.no_amount': 'No amount yet. A person is checking your claim.',
  TRACK_CHECKED_OK: 'All {passed} checks passed.',
  TRACK_CHECKED_FAILED: 'A required check did not pass.',
  TRACK_REFERRED_UNREADABLE: 'The slip could not be read clearly.',
  TRACK_REFERRED_NAME: 'The name on the slip does not match your KYC.',
  TRACK_REFERRED_DATES: 'The slip dates do not match the days your shop was closed.',
  TRACK_REFERRED_DAYS: 'This claim covers more days than are paid automatically.',
  TRACK_DECIDED_AUTO: 'Approved {amount}',
  TRACK_DECIDED_OFFICER: 'Approved by a claims officer',
  TRACK_PAID_PENDING: '{amount} is on its way, with the next settlement.',
  TRACK_PAID_ETA: 'Credit in about {minutes} minutes (demo clock).',
  TRACK_PAID_FAILED: 'The payout did not go through. Please talk to our team.',
  TRACK_EDI_REQUESTED: 'We asked your lender. The lender decides.',
  TRACK_EDI_REFUSED: 'Not available. Your instalment is due as usual.',
  TRACK_EDI_NO_RESPONSE: 'We could not reach your lender. Your instalment is due as usual.',
  TRACK_EDI_NONE: 'No loan on file',
  TRACK_DISPUTE_OPEN: 'Question open · case {case_id}. You will hear back within {sla_hours} hours.',
  TRACK_DISPUTE_CLOSED: 'Our team checked it. The amount paid stays {amount}.',
  CASE_CHIP: 'Sent to a claims officer · case {case_id}', // English in every language: the catalogue has no Hindi line
  'sim.payment': 'SIMULATED payment. No real money moves.',
  'sim.lender': 'SIMULATED lender. The answer comes from the demo rules.',
  'tracker.steps_label': 'Claim steps', // proposed
  'tracker.live_step': '{step}: {state}', // proposed
  'tracker.about_claim': 'About claim {claim_id}', // proposed
  'tracker.officer_note': 'Note from our team', // proposed
  'why.row.expected_day': 'Your usual day', // proposed
  'why.row.area_index': 'Area index', // proposed
  'why.row.area_drop': 'Area drop', // proposed
  'why.row.days': 'Days claimed', // proposed
  'why.row.share': "Chhatri's share", // proposed
  'why.row.cap': 'Daily limit', // proposed
  'why.row.amount': 'Your payout', // proposed
  'why.value.half': 'Half', // proposed
  'why.person_heading': 'Why a person is checking', // proposed
  'receipt.title.record': 'Your decision record',
  'receipt.row.decision': 'Decision',
  'receipt.row.rules': 'Rules version',
  'receipt.row.decided_at': 'Decided',
  'receipt.row.decided_by': 'Decided by',
  'receipt.row.formula': 'How it was worked out',
  'receipt.row.sources': 'Where each number came from',
  'receipt.row.checks': 'Checks',
  'receipt.row.paid_at': 'Credited',
  'receipt.row.pending': 'Credit pending',
  'receipt.row.audit': 'Audit entry (first {n} characters)',
  'receipt.row.what_changes': 'What would have changed this',
  'receipt.row.disagree': 'If you disagree',
  'receipt.row.payout': 'Payout',
  'receipt.row.lender': "Lender's answer",
  'receipt.row.clauses': 'Policy clauses used',
  'receipt.by.engine': 'An automatic rules check (code, not AI)',
  'receipt.by.officer': 'A claims officer',
  'receipt.btn.print': 'Print or save as PDF',
  'receipt.check_log': 'Check the log',
  'receipt.log.ok': 'Log unbroken, {entries} entries',
  'receipt.log.broken': 'The log is broken at entry {seq}.',
  'receipt.print.header': 'Chhatri · decision receipt · prototype · SIMULATED data',
  'receipt.simulated': 'SIMULATED receipt. The data and the payout are not real.',
  'receipt.footer': 'This receipt explains one decision. It is not a policy document.',
  'receipt.checks.show': 'Show the checks', // proposed
  'receipt.checks.hide': 'Hide the checks', // proposed
  'receipt.check.observed': 'What we found', // proposed
  'receipt.check.required': 'What is needed', // proposed
  'receipt.lender.granted': 'Your lender has paused the {instalment} instalment due on {date}. It moves to the end of your loan with no penalty.', // adapted from HOLIDAY_GRANTED_ON
  'src.RULES': 'Chhatri rules {rules_version}',
  'src.CLAUSE': 'Policy clause {clause}',
  'src.ALERT': 'Weather alert {alert_id}',
  'src.SALES_INDEX': 'Area sales index',
  'src.FORECAST': 'Your usual day, worked out from your past sales',
  'src.ZONE_BOUND': 'Usual range for your area',
  'src.COVER': 'Your cover record',
  'src.PREMIUM': 'Your premium payment',
  'src.KYC': 'Name on your Paytm account (KYC)',
  'src.SLIP': 'Hospital slip, as read',
  'src.SALES_DAY': 'Your sales for the day',
  'src.PAYOUT_HISTORY': 'Your earlier payouts',
  'src.LENDER': "Lender's answer",
  'chip.tap': 'Tap to see where this came from.',
  'badge.source_missing': 'Source missing',
  'chip.field.record': 'Record',
  'chip.field.time': 'Time',
  'chip.field.origin': 'Type of source',
  'chip.field.clause': 'Policy clause',
  'origin.CONFIG.hint': 'A fixed setting or document that comes with Chhatri.',
  'source.close': 'Close', // proposed
  'source.sheet_desc': 'Where this value came from.', // proposed
  'clause.C1': 'Words we use',
  'clause.C2': 'Rain and lost sales',
  'clause.C3': 'Hospital cash',
  'clause.C4': 'How much we pay',
  'clause.C5': 'When cover starts',
  'clause.C6': 'Premium and paying in advance',
  'clause.C7': 'What is not covered',
  'clause.C8': 'How claims are decided',
  'clause.C9': 'Questions and complaints',
  'clause.C10': 'Instalment holiday: your lender decides',
  'clause.C11': 'Your data and consent',
  'clause.C12': 'Cancelling and renewing',
  'chk.status.PASS': 'Passed',
  'chk.status.FAIL': 'Not met',
  'chk.status.UNSURE': 'Not sure',
  'chk.status.NOT_APPLICABLE': 'Not needed',
  'chk.status.WAIVED_BY_OFFICER': 'Cleared by a claims officer',
  CHK_COVER_IN_FORCE: 'Your cover was active',
  CHK_PREMIUM_PREPAID: 'The premium was paid in advance',
  CHK_COVER_BEFORE_ALERT: 'Your cover was bought before the alert',
  CHK_ALERT_ACTIVE: 'A weather alert covered your area',
  CHK_INDEX_QUORUM: 'Enough shops were counted in your area',
  CHK_BELOW_FLOOR: "Your area's sales stayed below the payout level",
  CHK_BELOW_MODEL_RANGE: 'The drop was bigger than a usual slow day',
  CHK_SILENCE_VERIFIED: 'Our records show no sales in your shop all day',
  CHK_SLIP_READABLE: 'The slip is clear',
  CHK_NAME_MATCHES_KYC: 'The name on the slip matches your Paytm account',
  CHK_DATES_MATCH: 'The slip dates cover the days your shop was closed',
  CHK_WITHIN_AUTO_LIMIT: 'The number of days is within the automatic limit',
  CHK_NOT_ALREADY_PAID: 'These days were not paid before',
  CHK_WITHIN_ANNUAL_LIMIT: 'Within your yearly limit',
  CF_TITLE: 'What would have changed this',
  CF_FOOTER: 'This explains this one decision. A future event is decided by the same checks when it happens.',
  'grv.step.PAYTM_DISPUTE': 'Our claims officer',
  'grv.step.INSURER_GRO': "The insurer's grievance officer",
  'grv.step.BIMA_BHAROSA': 'IRDAI Bima Bharosa portal',
  'grv.step.OMBUDSMAN': 'Insurance Ombudsman',
  'grv.clock.own': 'We reply within {sla_hours} hours.',
  'grv.clock.confirm.insurer': 'Response time to be confirmed with the insurer.',

  // Units of the numbers card (proposed)
  'explain.val.days': '{n} days',
  'explain.val.hours': '{n} hours',

  // More card 3.10 lines: the built DISPUTE_ACK and the REASON_ lines of the ten HARD checks (copy deck Appendix A), quoted.
  DISPUTE_ACK: "Okay, I'm sending this to our team. You'll hear back within 24 hours.", // built catalogue line, quoted
  REASON_COVER_IN_FORCE: "Your cover wasn't in force on that day.",
  REASON_PREMIUM_PREPAID: "The premium for that day hadn't been paid in advance.",
  REASON_SILENCE_VERIFIED: "Our records don't show your shop closed for that whole day.",
  REASON_NOT_ALREADY_PAID: 'That day has already been paid.',
  REASON_WITHIN_ANNUAL_LIMIT: 'It would go over the yearly limit.',
  REASON_COVER_BEFORE_ALERT: 'The cover was bought after the alert was issued.',
  REASON_ALERT_ACTIVE: 'There was no weather alert for your area at that time.',
  REASON_INDEX_QUORUM: 'Too few shops in your area to measure the drop.',
  REASON_BELOW_FLOOR: "Your area's sales didn't fall below the payout level.",
  REASON_BELOW_MODEL_RANGE: "Your area's sales stayed within their usual range.",

  // One more built REASON_ line (copy deck Appendix A), quoted.
  REASON_OFFICER_PERSONAL: "After checking the slip, this claim can't be paid.", // built catalogue line, quoted

  // Slip pre-check (N3, copy deck 12; the keys without a deck line are proposed and need the native review)
  SLIP_SHEET_TITLE: 'Send your hospital slip',
  SLIP_SHEET_HELP: 'Take one photo of the admission slip, the discharge paper or the bill. Use good light and keep the whole page in view.',
  SLIP_NOTICE: 'The photo may be sent to an AI reading service (Gemini or Sarvam) to be read. Please send a sample slip, not a real one.',
  SLIP_READING: 'Reading your slip…',
  SLIP_PRECHECK_SHOW: 'We have read your slip. Please check it. Is this right?',
  SLIP_FIELD_NAME: 'Patient',
  SLIP_FIELD_ADMITTED: 'Admitted',
  SLIP_FIELD_DISCHARGED: 'Discharged',
  SLIP_FIELD_HOSPITAL: 'Hospital',
  SLIP_FIELD_NOT_ON_SLIP: 'Not on the slip',
  SLIP_NOTE_NO_DISCHARGE: 'There is no discharge date on the slip. If you are still in hospital, that is normal.',
  SLIP_NOTE_NAME_NOT_LATIN: 'The name is not in English letters, so our team will look at it.',
  SLIP_CHECK_READABLE_PASS: 'The photo could be read',
  SLIP_CHECK_READABLE_WARN: 'The photo is not clear',
  SLIP_CHECK_NAME_PASS: 'The name is on the slip',
  SLIP_CHECK_NAME_WARN: 'The name is not clear',
  SLIP_CHECK_DATES_PASS: 'The admission date is on the slip',
  SLIP_CHECK_DATES_WARN: 'The admission date is not clear',
  SLIP_ACTION_CONFIRM: 'Yes, this is right',
  SLIP_ACTION_RETAKE: 'Send another photo',
  SLIP_ACTION_TEAM: 'Send to our team',
  SLIP_RETAKE_DOCUMENT: 'This does not look like a hospital document. Please send a photo of the admission slip, the discharge paper or the bill.',
  SLIP_RETAKE_CLEAR: 'The photo is not clear. Please take it in good light, with the slip flat and fully in view.',
  SLIP_RETAKE_NAME: 'The patient\'s name is not clear. Please send a photo where the whole name is in view.',
  SLIP_RETAKE_DATE: 'The admission date is not clear. Please send a photo where the whole date is in view.',
  SLIP_NO_READ: 'We could not read the slip just now. You can send it to our team, who will look at it.',
  SLIP_PHOTO_LIMIT: 'You have already sent several photos. Please send this one to our team now.',
  SLIP_CONSENT_NEEDED: 'We need your OK before we read a slip. Open the app and send your slip there. It will ask for your OK first.',
  'slip.err.too_big': 'The photo is too big. The limit is {max_mb} MB.',
  'slip.err.bad_type': 'Please send a JPG, PNG or WebP photo.',
  'slip.err.damaged': 'This photo cannot be opened. Please choose another one.',
  'slip.working': 'Checking your claim…',
  'sim.slip': 'SIMULATED slip reading. A fixed result is used for the demo slips.',
  'slip.take_photo': 'Take a photo',
  'slip.choose_gallery': 'Choose from the gallery',
  'slip.cancel': 'Cancel',
  'slip.details': 'Details',
  'slip.details.provider': 'Read by: {provider}',
  'slip.details.model': 'Model: {model}',
  'slip.details.reason': 'Reason: {reason}',
  'slip.what_read': 'What we could read',
  'slip.not_clear': 'not clear',
  'slip.demo.title': 'Demo slips',
  'slip.demo.good': 'Use the demo slip',
  'slip.demo.blurry': 'Use a blurry demo slip',
  'slip.help_row': 'Send your hospital slip',
  'slip.err.conflict': 'There is no open check-in for a slip right now, or the claim was already sent.',
  'slip.err.limit': 'Several photos have been sent already. Please send the slip to our team.',
  // Rights screens: titles of N5 and N6 (copy deck 13.1, 14.4 and 14.5); the rest is in copy/rights.ts
  'grv.title': 'Complaints and escalation',
  'grv.error.no_decision': 'There is no payout or decision on your account yet, so there is nothing to complain about here. Your claim tracker shows where things stand.',
  'grv.error.no_review': 'No claim of yours is waiting for review right now.',
  'consent.title': 'My data and consent',
  'activity.title': 'What was used',
} as const

export type CopyKey = keyof typeof en
