/**
 * Hindi strings of the mini-app (default language). Complete: the type demands every key of en.ts, and
 * copy.test.ts checks the placeholders. Lines quoted from the copy deck keep its Hindi; lines marked "proposed"
 * in en.ts are proposed here too and need the native review (fs-04 open question 1).
 */
import type { CopyKey } from './en'

export const hi: Readonly<Record<CopyKey, string>> = {
  // Shell and settings (copy deck 2.1)
  'nav.home': 'होम',
  'nav.claims': 'दावे',
  'nav.help': 'मदद',
  'app.name': 'छतरी',
  'app.tagline': 'Paytm for Business में छतरी',
  'app.clock': 'डेमो: {time}',
  'app.fullscreen': 'पूरी स्क्रीन पर खोलें',
  'clock.sheet.title': 'डेमो की तारीख़ और समय',
  'clock.sheet.note': 'डेमो की घड़ी आगे-पीछे करें। यह रीप्ले काल्पनिक है।',
  'clock.sheet.play': 'चलाएँ',
  'clock.sheet.pause': 'रोकें',
  'clock.sheet.start': 'शुरुआत पर वापस',
  'clock.chapter.alert': 'अलर्ट',
  'clock.chapter.trigger': 'ट्रिगर',
  'clock.chapter.paid': 'भुगतान',
  'clock.chapter.instalment': 'किस्त',
  'clock.chapter.checkin': 'हालचाल',
  'clock.chapter.cover': 'कवर माँगा',
  'lang.label': 'भाषा',
  'lang.hi': 'हिंदी',
  'lang.en': 'English',
  'lang.mr': 'मराठी',
  'lang.fallback_note': 'कुछ पाठ हिंदी में दिखाया गया है।',
  'settings.title': 'सेटिंग',
  'ask.title': 'छतरी से पूछें',

  // Screen titles (copy deck 2.2 to 4)
  'home.title': 'आपका कवर',
  'explain.title': 'मुझे किस नुकसान का कवर मिलता है?',
  'buy.title': 'कवर लें',
  'tracker.title': 'आपके दावे',
  'why.title': 'मुझे इतने ही पैसे क्यों मिले?',
  'receipt.title': 'आपके भुगतान की रसीद',

  // States (copy deck 15)
  'empty.claims':
    'अभी कोई दावा नहीं है। मौसम अलर्ट के दौरान आपके इलाके की बिक्री गिरे, तो छतरी आपके लिए दावा शुरू करती है। आपकी दुकान में पूरे दिन बिक्री न हो, तो छतरी आपसे पूछेगी कि सब ठीक है या नहीं।',
  'empty.cover': 'अभी आपका कोई कवर नहीं है।',
  'empty.receipt': 'अभी कोई रसीद नहीं है। भुगतान जमा होने के बाद रसीद दिखती है।',
  'error.title': 'यह लोड नहीं हो सका',
  'error.generic': 'कुछ गड़बड़ हो गई। फिर से कोशिश करें।',
  'error.retry': 'फिर से कोशिश करें',
  'error.code': 'त्रुटि कोड: {code}',
  'error.network': 'अभी कनेक्ट नहीं हो पा रहा। अपना इंटरनेट देखिए और फिर से कोशिश कीजिए।',
  'error.timeout': 'इसमें बहुत समय लग रहा है। कृपया थोड़ी देर बाद फिर से कोशिश करें।',
  'error.not_found': 'यह नहीं मिला। हो सकता है यह हटा दिया गया हो, या लिंक ग़लत हो।',
  'offline.banner': 'ऑफ़लाइन। {time} का डेटा दिख रहा है।',
  'offline.blocked': 'इसके लिए इंटरनेट चाहिए। ऑनलाइन होने पर फिर से कोशिश करें।',
  'offline.static': 'यह स्टैटिक डेमो है। डेटा बनावटी है। कुछ भी कहीं नहीं भेजा जाता।',
  'explain.btn.got_it': 'समझ गया',
  'sim.banner': 'SIMULATED। यह डेमो डेटा है। असली पैसा, संदेश या भुगतान नहीं जाता।',

  // Shell labels (proposed)
  'app.frame_label': 'छतरी ऐप, SIMULATED',
  'app.tabs': 'मुख्य टैब',
  'app.nba': 'अगला कदम',
  'app.back': 'वापस',
  'app.unknown_merchant': 'दुकानदार नहीं मिला',
  'state.loading': 'लोड हो रहा है',

  // Home and cover card (copy deck 2.2)
  'home.greeting': 'नमस्ते, {name} जी',
  'cover.status.pending_payment': 'पहले भुगतान का इंतज़ार',
  'cover.status.waiting': '{date} से शुरू होगा',
  'cover.status.active': 'चालू',
  'cover.status.active_unpaid': 'चालू, आगे के दिनों का प्रीमियम जमा नहीं',
  'cover.status.lapsed': 'बंद',
  'cover.status.cancelled': 'रद्द',
  'home.row.zone': 'आपका इलाका',
  'home.row.premium_per_day': 'रोज़ का प्रीमियम',
  'home.row.paid_through': 'इस तारीख़ तक जमा',
  'home.row.starts_on': 'कवर शुरू',
  'home.row.instalment': 'रोज़ की लोन किस्त',
  'home.used': 'पिछले {window_days} दिनों में इस्तेमाल: {used} / {limit}',
  'home.expected': 'आज की अनुमानित बिक्री',
  'home.latest': 'आपका ताज़ा दावा',
  'home.btn.coverage': 'मुझे किस नुकसान का कवर मिलता है?',
  'home.btn.buy': 'कवर लें',
  'home.btn.claims': 'मेरे दावे देखें',
  'home.btn.ask': 'छतरी से पूछें',
  'home.alert.banner': 'अलर्ट {alert_id} · {valid_from} से {valid_to} तक',
  'home.alert.covered': 'आपके इलाके के लिए मौसम अलर्ट चालू है। छतरी आपके इलाके की बिक्री पर नज़र रख रही है। आपको कुछ करने की ज़रूरत नहीं।',
  'home.alert.not_covered': 'आपके इलाके के लिए मौसम अलर्ट चालू है। नया कवर वेटिंग पीरियड के बाद शुरू होता है, इसलिए यह इस अलर्ट पर लागू नहीं होगा।',
  'alert.id': 'अलर्ट {alert_id}',

  // Coverage explainer (copy deck 2.3)
  'explain.numbers.title': 'आपका कवर, आँकड़ों में',
  'explain.num.share': 'खोई हुई बिक्री में छतरी का हिस्सा',
  'explain.num.area_cap': 'रोज़ की सीमा, बारिश',
  'explain.num.personal_cap': 'रोज़ की सीमा, अस्पताल',
  'explain.num.annual': 'साल की सीमा',
  'explain.num.waiting': 'वेटिंग पीरियड',
  'explain.num.lookahead': 'इतने घंटे आगे तक अलर्ट देखे जाते हैं',
  'explain.num.first_days': 'पहला भुगतान इतने दिन के लिए',
  'explain.c2.title': 'बारिश से बिक्री का नुकसान',
  'explain.c2.body':
    'जब मौसम अलर्ट चालू हो, आपके इलाके की बिक्री लगातार {hours} घंटे आम स्तर के {floor_pct}% से नीचे रहे, और गिरावट आम धीमे दिन से ज़्यादा हो, तब छतरी आपकी दुकान की खोई हुई बिक्री का {share_pct}% देती है। यह हिसाब आपके आम दिन और इलाके की गिरावट से बनता है। एक दिन में ज़्यादा से ज़्यादा {area_cap}। आपको दावा नहीं करना पड़ता।',
  'explain.c2.example':
    'एक चाय की दुकान मंगलवार को आम तौर पर ₹4,380 बेचती है। एक बारिश वाले मंगलवार को इलाके की बिक्री 63% गिरी। खोई हुई बिक्री का आधा ₹1,379.70 है, जो ₹1,380 बनता है, इसलिए दुकान को ₹1,380 मिले।',
  'explain.c3.title': 'अस्पताल में आय का नुकसान',
  'explain.c3.body':
    'अगर आपकी दुकान में पूरे दिन बिक्री न हो, तो छतरी आपसे पूछती है कि सब ठीक है या नहीं। अगर आप अस्पताल में हैं, तो अस्पताल की पर्ची की एक फ़ोटो भेजें। पर्ची ठीक निकलने पर छतरी आपके आम दिन का {share_pct}% देती है, एक दिन में ज़्यादा से ज़्यादा {personal_cap}, और ज़्यादा से ज़्यादा {max_auto_days} दिन तक। इससे लंबे दावे को कोई व्यक्ति देखता है।',
  'explain.c3.example':
    'एक दुकान बुधवार को आम तौर पर ₹4,300 बेचती है। मालिक अस्पताल में थे और उस दिन दुकान में कोई बिक्री नहीं हुई। ₹4,300 का आधा ₹2,150 है, पर एक दिन की सीमा ₹1,500 है, इसलिए उस दिन के ₹1,500 दिए गए।',
  'explain.c4.title': 'छतरी कितना देती है',
  'explain.c4.body':
    'छतरी आपकी खोई हुई बिक्री का {share_pct}% देती है। एक दिन में ज़्यादा से ज़्यादा बारिश के लिए {area_cap} और अस्पताल के लिए {personal_cap}। अस्पताल का भुगतान बिना समीक्षा के ज़्यादा से ज़्यादा {max_auto_days} दिन तक होता है। किसी भी {window_days} दिनों में सारे भुगतान जोड़ने पर {annual_limit} से ज़्यादा नहीं होते।',
  'explain.c5.title': 'कवर कब शुरू होता है',
  'explain.c5.body':
    'नया कवर माँगने के {waiting_days} दिन बाद शुरू होता है। अगर आपके इलाके के लिए अलर्ट चालू है, या जारी हो चुका है और {lookahead_hours} घंटे में शुरू होगा, तो कवर तुरंत शुरू नहीं हो सकता। आगे के लिए कवर आप फिर भी ले सकते हैं। अलर्ट जारी होने के बाद लिया गया कवर उस अलर्ट के लिए कभी भुगतान नहीं करता।',
  'explain.c5.example': 'रमेश सोमवार 18 अगस्त को 18:00 बजे कवर माँगते हैं। उनका कवर 25 अगस्त से शुरू होता है।',
  'explain.c6.title': 'प्रीमियम और पहले से जमा दिन',
  'explain.c6.body':
    'पहला भुगतान {first_days} दिन के लिए होता है। उसके बाद शाम का सेटलमेंट आपकी स्थायी सहमति से अगले दिन का प्रीमियम काट लेता है। कवर उन्हीं दिनों काम करता है जिनका प्रीमियम पहले से जमा हो।',
  'explain.c6.example': 'डेमो में ज़ोन 3 का प्रीमियम रोज़ ₹14.16 है, इसलिए 30 दिन के ₹424.80 होते हैं। असली कीमत अभी तय नहीं हुई है।',
  'explain.c7.title': 'दावे का भुगतान कब नहीं होता',
  'explain.c7.body':
    'जब कोई ज़रूरी जाँच पास नहीं होती, तब दावे का भुगतान नहीं होता। नीचे वे कारण हैं जो छतरी बताती है। जिस बात पर सिस्टम को यकीन न हो, उसे कोई व्यक्ति देखता है। यह इनकार नहीं है।',
  'explain.c10.title': 'आपकी लोन किस्त',
  'explain.c10.body': 'भुगतान के बाद छतरी आपके लेंडर से आपकी अगली किस्त रोकने को कहती है। फ़ैसला लेंडर का होता है, छतरी का नहीं।',
  'explain.example.title': 'उदाहरण',
  'explain.example.sim': 'SIMULATED रीप्ले का उदाहरण',
  'explain.price.covered': 'आपकी कीमत: {per_day} प्रति दिन।',
  'explain.price.uncovered': 'कवर लें पर टैप करने पर आपको अपनी कीमत दिखेगी।',
  'explain.price.prototype': 'प्रोटोटाइप की कीमत। असली कीमत अभी तय नहीं हुई है।',
  'explain.no_forms': 'बारिश के दावे में कोई फ़ॉर्म नहीं। अस्पताल के दावे में पर्ची की एक फ़ोटो चाहिए।',
  'explain.rules_note': 'ये डेमो नियम हैं ({rules_version})। ये सिर्फ़ उदाहरण के लिए हैं। असली शर्तें साझेदार बीमा कंपनी तय करेगी।',
  'explain.terms_hint': 'किसी रेखांकित शब्द पर टैप करें, उसका मतलब दिखेगा।',
  'reason.cover_in_force': 'उस दिन आपका कवर चालू नहीं था।',
  'reason.premium_prepaid': 'उस दिन का प्रीमियम पहले से जमा नहीं था।',
  'reason.silence_verified': 'हमारे रिकॉर्ड में उस दिन दुकान पूरे दिन बंद नहीं दिखी।',
  'reason.not_already_paid': 'उस दिन का भुगतान पहले ही हो चुका है।',
  'reason.within_annual_limit': 'इससे साल की सीमा पार हो जाती।',
  'reason.cover_before_alert': 'कवर अलर्ट जारी होने के बाद लिया गया था।',
  'reason.alert_active': 'उस समय आपके इलाके में कोई मौसम अलर्ट नहीं था।',
  'reason.index_quorum': 'आपके इलाके में हिसाब के लिए काफ़ी दुकानें नहीं थीं।',
  'reason.below_floor': 'आपके इलाके की बिक्री भुगतान की सीमा से नीचे नहीं गिरी।',
  'reason.below_model_range': 'आपके इलाके की बिक्री आम दायरे के अंदर रही।',

  // Get cover (copy deck 2.4, proposed lines marked)
  'buy.intro': 'नया कवर हमेशा माँगने के {waiting_days} दिन बाद शुरू होता है।',
  'buy.check': 'कीमत और शुरू होने की तारीख़ देखें',
  'buy.outcome.ok': 'कवर {date} से शुरू होगा',
  'buy.outcome.blocked': 'अभी रुका है। कवर {date} से शुरू होगा।',
  'buy.row.starts': 'कवर शुरू',
  'buy.row.per_day': 'रोज़ का प्रीमियम',
  'buy.row.first_payment': 'पहला भुगतान ({first_days} दिन)',
  'buy.blocked_note': 'अलर्ट जारी होने के बाद लिया गया कवर उस अलर्ट के लिए भुगतान नहीं करता। आप आगे के लिए कवर फिर भी ले सकते हैं।',
  'buy.consent.notice': 'छतरी आपकी बिक्री का डेटा दावे तय करने और आपका प्रीमियम बनाने में इस्तेमाल करती है।',
  'buy.consent.text': 'भुगतान से पहले: छतरी आपकी बिक्री के डेटा से दावे तय करती है और प्रीमियम तय करती है। पहले भुगतान के बाद छतरी आपके रोज़ के सेटलमेंट से अगले दिन का प्रीमियम काटती है। अस्पताल की पर्ची छतरी तब पढ़ती है जब आप भेजें, और सिर्फ़ उसी दावे के लिए। आप इनमें से हर एक को ऐप में मदद, मेरा डेटा और सहमति में बंद कर सकते हैं। यह एक प्रोटोटाइप है और डेटा काल्पनिक है।',
  'buy.consent.version': 'सूचना संस्करण {version}',
  'buy.consent.box.SALES_DATA_FOR_CLAIM': 'मैं सहमत हूँ: छतरी मेरी बिक्री का डेटा दावे तय करने और प्रीमियम तय करने में इस्तेमाल कर सकती है।',
  'buy.consent.box.SETTLEMENT_DEDUCTION': 'मैं सहमत हूँ: पहले भुगतान के बाद छतरी मेरे रोज़ के सेटलमेंट से अगले दिन का प्रीमियम काट सकती है।',
  'buy.consent.box.SLIP_DATA_FOR_HOSPITAL_CLAIM': 'मैं सहमत हूँ: जब मैं अस्पताल की पर्ची भेजूँ, छतरी उसे पढ़ सकती है।',
  'buy.consent.tag.required': 'कवर के लिए ज़रूरी',
  'buy.consent.tag.optional': 'ज़रूरी नहीं',
  'buy.consent.hint': 'आगे बढ़ने के लिए “कवर के लिए ज़रूरी” वाले दोनों बॉक्स चुनें।',
  'buy.consent.error': 'सूचना बदल गई है। कृपया उसे फिर से पढ़ें।',
  'buy.pay': 'Paytm से भुगतान करें',
  'buy.simulate': 'भुगतान का सिमुलेशन करें',
  'buy.pending': 'आपके भुगतान का इंतज़ार है। भुगतान आते ही यह पेज बदल जाएगा।',
  'buy.link.simulated': 'SIMULATED भुगतान लिंक। असली पैसा नहीं जाता।',
  'buy.paid': 'आपका भुगतान आ गया।',
  'buy.link_label': 'भुगतान लिंक',
  'buy.link_unavailable': 'भुगतान लिंक अभी नहीं बन सका। थोड़ी देर बाद फिर से पूछिए।',
  'buy.needs_presenter': 'इस डेमो काम के लिए प्रस्तुतकर्ता का सेशन चाहिए।',
  'error.pay_failed': 'भुगतान नहीं हो पाया। कोई पैसा नहीं कटा। आप फिर से कोशिश कर सकते हैं।',

  // Help, Settings and Language (copy deck 2.1, 5.2; proposed lines marked)
  'help.about.title': 'इस प्रोटोटाइप के बारे में',
  'help.about.text':
    'यह एक प्रोटोटाइप है। अनिल जाधव समेत यहाँ के सभी दुकानदार काल्पनिक हैं। SIMULATED लिखी हर चीज़ असली नहीं है: बिक्री, अलर्ट, KYC, भुगतान, लेंडर, Soundbox, WhatsApp और Paytm लिंक।',
  'origin.LIVE.hint': 'यह असली कनेक्शन से आया है।',
  'origin.SIMULATED.hint': 'डेमो डेटा। असली पैसा, संदेश या भुगतान नहीं जाता।',
  'mode.FALLBACK.hint': 'आम सेवा उपलब्ध नहीं थी, इसलिए बैकअप इस्तेमाल हो रहा है।',
  'help.glossary.title': 'बीमा के शब्द, आसान भाषा में',
  'help.dispute.hint': 'अगर कोई रकम गलत लगे, तो दावा खोलें और “यह ग़लत है” दबाएँ।',
  'lang.preview': 'पूर्वावलोकन',
  'lang.native_hint': 'हर भाषा अपनी लिपि में दिखाई गई है।',

  // Jargon lens (copy deck 7)
  'lens.title': 'इस शब्द का मतलब क्या है?',
  'lens.plain': 'सरल शब्दों में',
  'lens.example': 'उदाहरण',
  'lens.close': 'बंद करें',
  'lens.footer': 'यह शब्द को आसान भाषा में समझाता है। सही शर्तें पॉलिसी के शब्दों में हैं।',
  'jargon.waiting_period.term': 'वेटिंग पीरियड',
  'jargon.waiting_period.what': 'नया कवर माँगने के {waiting_days} दिन बाद शुरू होता है। तब तक यह भुगतान नहीं करता।',
  'jargon.waiting_period.example': 'रमेश सोमवार 18 अगस्त को कवर माँगते हैं। उनका कवर 25 अगस्त से शुरू होता है।',
  'jargon.alert.term': 'मौसम अलर्ट',
  'jargon.alert.what': 'आपके इलाके के लिए मौसम की चेतावनी। अलर्ट जारी होने के बाद लिया गया कवर उस अलर्ट के लिए भुगतान नहीं करता।',
  'jargon.alert.example': 'अलर्ट A-20250818-01 सोमवार 18 अगस्त को 17:30 बजे अगले दिन के लिए जारी हुआ था।',
  'jargon.expected_day.term': 'आपका आम दिन',
  'jargon.expected_day.what': 'हफ़्ते के इस दिन छतरी के हिसाब से आपकी दुकान की आम बिक्री, जो आपकी पिछली बिक्री से निकाली जाती है।',
  'jargon.expected_day.example': 'अनिल का आम मंगलवार: ₹4,380।',
  'jargon.area_drop.term': 'इलाके की गिरावट',
  'jargon.area_drop.what': 'आपके इलाके की दुकानों की बिक्री उम्मीद से कितने प्रतिशत गिरी।',
  'jargon.area_drop.example': '19 अगस्त को ज़ोन 7 उम्मीद का 37% रहा, यानी 63% की गिरावट।',
  'jargon.payout_share.term': 'छतरी का हिस्सा',
  'jargon.payout_share.what': 'छतरी आपकी खोई हुई बिक्री का {share_pct}% देती है।',
  'jargon.payout_share.example': '½ × ₹4,380 × 63% = ₹1,380: आधा × आपका आम दिन × इलाके की गिरावट।',
  'jargon.daily_cap.term': 'रोज़ की सीमा',
  'jargon.daily_cap.what': 'एक दिन के लिए छतरी जितना ज़्यादा से ज़्यादा देती है: बारिश के लिए {area_cap} और अस्पताल के लिए {personal_cap}।',
  'jargon.daily_cap.example': '₹4,300 के दिन का आधा ₹2,150 है, पर अस्पताल की रोज़ की सीमा ₹1,500 है, इसलिए ₹1,500 दिए जाते हैं।',
  'jargon.annual_limit.term': 'साल की सीमा',
  'jargon.annual_limit.what': 'किसी भी {window_days} दिनों में छतरी आपको जितना ज़्यादा से ज़्यादा देती है: {annual_limit}।',
  'jargon.annual_limit.example': 'जो दावा आपको सीमा के ऊपर ले जाए, उसका भुगतान नहीं होता।',
  'jargon.premium.term': 'प्रीमियम',
  'jargon.premium.what': 'कवर के लिए आप हर दिन जो थोड़ी रकम देते हैं।',
  'jargon.premium.example': 'डेमो में ज़ोन 3 का प्रीमियम रोज़ ₹14.16 है, इसलिए 30 दिन के ₹424.80। असली कीमत अभी तय नहीं हुई है।',
  'jargon.prepaid_through.term': 'इस तारीख़ तक जमा',
  'jargon.prepaid_through.what': 'कवर उन दिनों काम करता है जिनका प्रीमियम पहले से जमा हो। यह आख़िरी जमा दिन है।',
  'jargon.prepaid_through.example': 'रमेश के ₹424.80 से 30 दिन का प्रीमियम जमा होता है, 25 अगस्त से 23 सितंबर तक।',
  'jargon.settlement.term': 'सेटलमेंट',
  'jargon.settlement.what': 'आपकी Paytm बिक्री का आपके बैंक खाते में जाना।',
  'jargon.settlement.example': 'अनिल के ₹1,380 17:04 पर सेटलमेंट के साथ आए (SIMULATED)।',
  'jargon.edi_holiday.term': 'किस्त की छुट्टी (EDI)',
  'jargon.edi_holiday.what':
    'अगर आप अपना लोन हर दिन की किस्त (EDI) से चुकाते हैं, तो आपका लेंडर एक दिन की किस्त रोक सकता है। फ़ैसला लेंडर का होता है, छतरी का नहीं।',
  'jargon.edi_holiday.example': 'अनिल की ₹600 की किस्त: छतरी पूछती है, लेंडर जवाब देता है।',
  'jargon.kyc.term': 'KYC',
  'jargon.kyc.what': 'आपके बारे में Paytm के पास पहले से मौजूद पहचान की जानकारी, जैसे आपका नाम।',
  'jargon.kyc.example': 'अस्पताल की पर्ची का नाम आपके KYC नाम से मिलाया जाता है। {name_match_min} या उससे ज़्यादा स्कोर पर नाम मेल खाता है।',
  'jargon.referred.term': 'हमारी टीम देख रही है',
  'jargon.referred.what': 'हमारी टीम का कोई व्यक्ति फ़ैसला करेगा। यह इनकार नहीं है। {sla_hours} घंटे में जवाब मिलेगा।',
  'jargon.referred.example': 'पर्ची पर नाम "सुनील पवार" KYC से मेल नहीं खाया, इसलिए केस C-2291 अधिकारी के पास गया।',
  'jargon.audit_fingerprint.term': 'ऑडिट कोड',
  'jargon.audit_fingerprint.what':
    'हर फ़ैसला एक जुड़ी हुई कड़ियों वाले लॉग में लिखा जाता है। पुरानी लाइन बदलने से कड़ी टूट जाती है। यह कोड इस फ़ैसले की लाइन की पहचान है।',
  'jargon.audit_fingerprint.example': '"लॉग जाँचें" बताता है कि पूरा लॉग सही है या नहीं।',
  'jargon.rules_version.term': 'नियमों का संस्करण',
  'jargon.rules_version.what': 'इस फ़ैसले में इस्तेमाल हुए नियमों का संस्करण।',
  'jargon.rules_version.example': 'उदाहरण: {rules_version}।',

  // Next best action: a sentence and a button for each rule (copy deck 8.1, wave 1)
  'nba.get_cover_from_coverage': 'कवर लेना है? कीमत और शुरू होने की तारीख़ देखें।',
  'nba.get_cover_from_coverage.btn': 'कवर लें',
  'nba.see_claims': 'देखिए छतरी ने आपके लिए क्या किया।',
  'nba.see_claims.btn': 'मेरे दावे देखें',
  'nba.home_from_coverage': 'कवर के बारे में बस इतना ही।',
  'nba.home_from_coverage.btn': 'होम पर वापस',
  'nba.check_price': 'पहले अपनी कीमत और शुरू होने की तारीख़ देखें।',
  'nba.check_price.btn': 'कीमत और शुरू होने की तारीख़ देखें',
  'nba.pay': 'कवर शुरू करने के लिए पहला भुगतान करें।',
  'nba.pay.btn': 'Paytm से भुगतान करें',
  'nba.home_after_paid': 'आपका भुगतान आ गया।',
  'nba.home_after_paid.btn': 'होम पर वापस',
  'nba.home_when_covered': 'आपके पास पहले से कवर है।',
  'nba.home_when_covered.btn': 'होम पर वापस',
  'nba.open_latest': 'हर कदम देखने के लिए अपना ताज़ा दावा खोलें।',
  'nba.open_latest.btn': 'ताज़ा दावा खोलें',
  'nba.see_coverage_empty': 'अभी कोई दावा नहीं। देखें क्या कवर है।',
  'nba.see_coverage_empty.btn': 'क्या कवर है, देखें',
  'nba.wait_for_officer': 'क्लेम अधिकारी इसे देख रहे हैं। {sla_hours} घंटे में जवाब मिलेगा।',
  'nba.wait_for_officer.btn': 'दावों पर वापस',
  'nba.see_why': 'आपके {amount} जमा हो गए हैं। देखिए हिसाब कैसे बना।',
  'nba.see_why.btn': 'इतने पैसे क्यों?',
  'nba.back_to_claims': 'इस दावे के बारे में बस इतना ही।',
  'nba.back_to_claims.btn': 'दावों पर वापस',
  'nba.see_receipt': 'इस फ़ैसले की रसीद अपने पास रखें।',
  'nba.see_receipt.btn': 'रसीद देखें',
  'nba.disagree': 'सहमत नहीं हैं? हमें बताइए।',
  'nba.disagree.btn': 'यह ग़लत है',
  'nba.home_after_language': 'भाषा सेव हो गई।',
  'nba.home_after_language.btn': 'होम पर वापस',
  'nba.see_dispute_case': 'आपका केस क्लेम अधिकारी के पास है। {sla_hours} घंटे में जवाब मिलेगा।',
  'nba.see_dispute_case.btn': 'मेरा केस देखें',
  'nba.see_referred_claim': 'क्लेम अधिकारी आपका दावा जाँच रहे हैं।',
  'nba.see_referred_claim.btn': 'मेरा दावा देखें',
  'nba.see_coverage_waiting': 'आपका कवर {starts_on} से शुरू होगा।',
  'nba.see_coverage_waiting.btn': 'क्या कवर है, देखें',
  'nba.get_cover': 'अभी आपके पास कवर नहीं है।',
  'nba.get_cover.btn': 'कवर लें',
  'nba.see_premium': 'आगे के दिनों का प्रीमियम जमा नहीं है। देखिए यह कैसे काम करता है।',
  'nba.see_premium.btn': 'देखें यह कैसे काम करता है',
  'nba.alert_notice': 'आपके इलाके के लिए अलर्ट है। इलाके की बिक्री गिरे, तो छतरी अपने-आप आँकड़े जाँचती है।',
  'nba.alert_notice.btn': 'क्या कवर है, देखें',
  'nba.see_coverage': 'देखिए आपको किस नुकसान का कवर मिलता है।',
  'nba.see_coverage.btn': 'क्या कवर है, देखें',
  'nba.tick_consent': 'आगे बढ़ने के लिए “कवर के लिए ज़रूरी” वाले बॉक्स चुनें।',
  'nba.tick_consent.btn': 'बॉक्स पर जाएँ',
  'nba.send_slip': 'अपनी अस्पताल की पर्ची की एक फ़ोटो भेजें।',
  'nba.send_slip.btn': 'पर्ची की फ़ोटो भेजें',
  'nba.ask': 'कोई सवाल है? छतरी से पूछें।',
  'nba.ask.btn': 'छतरी से पूछें',

  // Labels shared with the claim screens (copy deck 3.1)
  'tracker.kind.area': 'बारिश से बिक्री का नुकसान',
  'tracker.kind.personal': 'अस्पताल में आय का नुकसान',
  'tracker.kind.dispute': 'भुगतान पर सवाल',
  'tracker.state.now': 'चल रहा है',
  'claim.status.approved_pending': 'मंज़ूर। पैसा आने वाला है।',
  'claim.status.paid': 'भुगतान हुआ',
  'claim.status.referred': 'हमारी टीम देख रही है',
  'claim.status.declined': 'भुगतान नहीं हुआ',
  'claim.status.waiting_slip': 'आपकी पर्ची का इंतज़ार',
  'claim.status.question_open': 'सवाल खुला है',
  'claim.status.question_closed': 'सवाल बंद। रकम वही रही।',

  // Claims, tracker, why and receipt (card 3.10): the deck's Hindi, quoted. A line marked "proposed" is new and needs the native review.
  'tracker.step.detected': 'पता चला',
  'tracker.step.checked': 'जाँच हुई',
  'tracker.step.decided': 'फ़ैसला हुआ',
  'tracker.step.paid': 'भुगतान हुआ',
  'tracker.step.edi': 'किस्त की छुट्टी (EDI)',
  'tracker.state.done': 'हो गया',
  'tracker.state.waiting': 'इंतज़ार',
  'tracker.state.na': 'ज़रूरी नहीं',
  'tracker.state.stopped': 'यहीं रुक गया',
  'tracker.clock.left': '{hours} घंटे बाकी',
  'tracker.clock.due': 'जवाब का समय: {time} तक',
  'tracker.clock.overdue': 'समय सीमा पार',
  'tracker.btn.receipt': 'रसीद देखें',
  'tracker.btn.wrong': 'यह ग़लत है',
  'tracker.btn.why': 'इतने पैसे क्यों?',
  'tracker.next.referred': 'आगे: कोई व्यक्ति फ़ैसला करेगा। {sla_hours} घंटे में जवाब मिलेगा।',
  'tracker.next.after_decided': 'आगे: पैसे सेटलमेंट के साथ जमा होते हैं।',
  'tracker.next.after_paid': 'आगे: अगर आपका लोन है, तो किस्त पर लेंडर फ़ैसला करता है।',
  'tracker.next.done': 'सभी कदम पूरे हुए। आपकी रसीद तैयार है।',
  'tracker.next.declined': 'आप कारण पूछ सकते हैं या हमारी टीम से बात कर सकते हैं।',
  'why.numbers': 'आपके आँकड़े',
  'why.no_amount': 'अभी कोई रकम नहीं है। कोई व्यक्ति आपका दावा जाँच रहा है।',
  TRACK_CHECKED_OK: 'सभी {passed} जाँचें पास हुईं।',
  TRACK_CHECKED_FAILED: 'एक ज़रूरी जाँच पास नहीं हुई।',
  TRACK_REFERRED_UNREADABLE: 'पर्ची साफ़ नहीं पढ़ी जा सकी।',
  TRACK_REFERRED_NAME: 'पर्ची का नाम आपके KYC से मेल नहीं खाता।',
  TRACK_REFERRED_DATES: 'पर्ची की तारीख़ें दुकान बंद रहने के दिनों से मेल नहीं खातीं।',
  TRACK_REFERRED_DAYS: 'यह दावा अपने-आप भुगतान के दिनों से ज़्यादा दिनों का है।',
  TRACK_DECIDED_AUTO: 'मंज़ूर {amount}',
  TRACK_DECIDED_OFFICER: 'क्लेम अधिकारी ने मंज़ूर किया',
  TRACK_PAID_PENDING: '{amount} अगले सेटलमेंट के साथ आ रहे हैं।',
  TRACK_PAID_ETA: 'लगभग {minutes} मिनट में जमा होगा (डेमो घड़ी)।',
  TRACK_PAID_FAILED: 'भुगतान नहीं हो पाया। कृपया हमारी टीम से बात करें।',
  TRACK_EDI_REQUESTED: 'हमने आपके लेंडर से कहा है। फ़ैसला लेंडर का होता है।',
  TRACK_EDI_REFUSED: 'उपलब्ध नहीं। आपकी किस्त हमेशा की तरह देय है।',
  TRACK_EDI_NO_RESPONSE: 'हम आपके लेंडर तक नहीं पहुँच सके। आपकी किस्त हमेशा की तरह देय है।',
  TRACK_EDI_NONE: 'कोई लोन दर्ज नहीं',
  TRACK_DISPUTE_OPEN: 'सवाल खुला है · केस {case_id}। {sla_hours} घंटे में जवाब मिलेगा।',
  TRACK_DISPUTE_CLOSED: 'हमारी टीम ने जाँच की। दिया गया भुगतान {amount} ही रहेगा।',
  CASE_CHIP: 'Sent to a claims officer · case {case_id}', // English in every language: the catalogue has no Hindi line
  'sim.payment': 'SIMULATED भुगतान। असली पैसा नहीं जाता।',
  'sim.lender': 'SIMULATED लेंडर। जवाब डेमो नियमों से आता है।',
  'tracker.steps_label': 'दावे के कदम', // proposed
  'tracker.live_step': '{step}: {state}', // proposed
  'tracker.about_claim': 'दावा {claim_id} के बारे में', // proposed
  'tracker.officer_note': 'हमारी टीम का नोट', // proposed
  'claim.next.title': 'आगे क्या होगा', // proposed
  'claim.next.money': '{amount} आपके सेटलमेंट के साथ {time} को जमा हुए।', // proposed
  'claim.next.wrong': 'अगर रकम गलत लगे, तो “यह ग़लत है” दबाएँ।', // proposed
  'claim.next.cover': 'आपका कवर जारी है। प्रीमियम {date} तक जमा है।', // proposed
  'why.row.expected_day': 'आपका आम दिन', // proposed
  'why.row.area_index': 'इलाके का इंडेक्स', // proposed
  'why.row.area_drop': 'इलाके की गिरावट', // proposed
  'why.row.days': 'दावे के दिन', // proposed
  'why.row.share': 'छतरी का हिस्सा', // proposed
  'why.row.cap': 'रोज़ की सीमा', // proposed
  'why.row.amount': 'आपका भुगतान', // proposed
  'why.value.half': 'आधा', // proposed
  'why.person_heading': 'कोई व्यक्ति क्यों जाँच रहा है', // proposed
  'receipt.title.record': 'आपके फ़ैसले का रिकॉर्ड',
  'receipt.row.decision': 'फ़ैसला',
  'receipt.row.rules': 'नियमों का संस्करण',
  'receipt.row.decided_at': 'फ़ैसले का समय',
  'receipt.row.decided_by': 'फ़ैसला किसने किया',
  'receipt.row.formula': 'हिसाब कैसे बना',
  'receipt.row.sources': 'हर आँकड़ा कहाँ से आया',
  'receipt.row.checks': 'जाँचें',
  'receipt.row.paid_at': 'जमा हुआ',
  'receipt.row.pending': 'जमा होना बाकी',
  'receipt.row.audit': 'ऑडिट एंट्री (पहले {n} अक्षर)',
  'receipt.row.what_changes': 'क्या बदलने पर नतीजा बदलता',
  'receipt.row.disagree': 'अगर आप सहमत नहीं हैं',
  'receipt.row.payout': 'भुगतान',
  'receipt.row.lender': 'लेंडर का जवाब',
  'receipt.row.clauses': 'इस्तेमाल हुए पॉलिसी खंड',
  'receipt.by.engine': 'नियमों की अपने-आप जाँच (कोड, AI नहीं)',
  'receipt.by.officer': 'क्लेम अधिकारी',
  'receipt.btn.print': 'प्रिंट करें या PDF बनाएँ',
  'receipt.check_log': 'लॉग जाँचें',
  'receipt.log.ok': 'लॉग सही है, {entries} एंट्री',
  'receipt.log.broken': 'लॉग एंट्री {seq} पर टूटा हुआ है।',
  'receipt.print.header': 'छतरी · फ़ैसले की रसीद · प्रोटोटाइप · SIMULATED डेटा',
  'receipt.simulated': 'SIMULATED रसीद। डेटा और भुगतान असली नहीं हैं।',
  'receipt.footer': 'यह रसीद एक फ़ैसले को समझाती है। यह पॉलिसी का दस्तावेज़ नहीं है।',
  'receipt.checks.show': 'जाँचें दिखाएँ', // proposed
  'receipt.checks.hide': 'जाँचें छिपाएँ', // proposed
  'receipt.check.observed': 'हमें क्या मिला', // proposed
  'receipt.check.required': 'क्या ज़रूरी था', // proposed
  'receipt.lender.granted': 'आपके लेंडर ने {date} की {instalment} की किस्त रोक दी है। वह आपके लोन के अंत में चली जाती है, कोई जुर्माना नहीं।', // adapted from HOLIDAY_GRANTED_ON
  'receipt.authority.title': 'इस भुगतान का फ़ैसला किसने किया', // proposed
  'receipt.authority.title.record': 'यह फ़ैसला किसने किया', // proposed
  'receipt.authority.engine': 'पॉलिसी इंजन', // proposed
  'receipt.authority.ai_label': 'AI का अधिकार', // proposed
  'receipt.authority.ai': 'कोई नहीं। AI इस फ़ैसले को समझा सकता है, पर भुगतान तय नहीं कर सकता और उसे बदल भी नहीं सकता।', // proposed
  'receipt.authority.verify': 'इस फ़ैसले की जाँच करें', // proposed
  'src.RULES': 'छतरी के नियम {rules_version}',
  'src.CLAUSE': 'पॉलिसी का खंड {clause}',
  'src.ALERT': 'मौसम अलर्ट {alert_id}',
  'src.SALES_INDEX': 'इलाके की बिक्री का हिसाब',
  'src.FORECAST': 'आपका आम दिन, आपकी पिछली बिक्री से निकाला गया',
  'src.ZONE_BOUND': 'आपके इलाके का आम दायरा',
  'src.COVER': 'आपके कवर का रिकॉर्ड',
  'src.PREMIUM': 'आपका प्रीमियम भुगतान',
  'src.KYC': 'आपके Paytm खाते का नाम (KYC)',
  'src.SLIP': 'अस्पताल की पर्ची, जैसी पढ़ी गई',
  'src.SALES_DAY': 'उस दिन की आपकी बिक्री',
  'src.PAYOUT_HISTORY': 'आपको पहले मिले भुगतान',
  'src.LENDER': 'लेंडर का जवाब',
  'chip.tap': 'यह कहाँ से आया, देखने के लिए टैप करें।',
  'badge.source_missing': 'स्रोत नहीं मिला',
  'chip.field.record': 'रिकॉर्ड',
  'chip.field.time': 'समय',
  'chip.field.origin': 'स्रोत का प्रकार',
  'chip.field.clause': 'पॉलिसी का खंड',
  'origin.CONFIG.hint': 'यह छतरी के साथ आने वाली तय सेटिंग या दस्तावेज़ है।',
  'source.close': 'बंद करें', // proposed
  'source.sheet_desc': 'यह मान कहाँ से आया।', // proposed
  'clause.C1': 'इस्तेमाल हुए शब्द',
  'clause.C2': 'बारिश से बिक्री का नुकसान',
  'clause.C3': 'अस्पताल में आय का नुकसान',
  'clause.C4': 'कितना भुगतान होता है',
  'clause.C5': 'कवर कब शुरू होता है',
  'clause.C6': 'प्रीमियम और पहले भुगतान',
  'clause.C7': 'क्या कवर नहीं है',
  'clause.C8': 'दावे कैसे तय होते हैं',
  'clause.C9': 'सवाल और शिकायतें',
  'clause.C10': 'किस्त की छुट्टी: लेंडर तय करता है',
  'clause.C11': 'आपका डेटा और सहमति',
  'clause.C12': 'रद्द करना और नवीनीकरण',
  'chk.status.PASS': 'पास',
  'chk.status.FAIL': 'पूरा नहीं हुआ',
  'chk.status.UNSURE': 'यकीन नहीं',
  'chk.status.NOT_APPLICABLE': 'ज़रूरी नहीं',
  'chk.status.WAIVED_BY_OFFICER': 'क्लेम अधिकारी ने आगे बढ़ाया',
  CHK_COVER_IN_FORCE: 'आपका कवर चालू था',
  CHK_PREMIUM_PREPAID: 'प्रीमियम पहले से जमा था',
  CHK_COVER_BEFORE_ALERT: 'आपका कवर अलर्ट से पहले खरीदा गया था',
  CHK_ALERT_ACTIVE: 'आपके इलाके में मौसम अलर्ट था',
  CHK_INDEX_QUORUM: 'आपके इलाके में काफ़ी दुकानें गिनी गईं',
  CHK_BELOW_FLOOR: 'आपके इलाके की बिक्री भुगतान की सीमा से नीचे रही',
  CHK_BELOW_MODEL_RANGE: 'गिरावट आम धीमे दिन से ज़्यादा थी',
  CHK_SILENCE_VERIFIED: 'हमारे रिकॉर्ड में आपकी दुकान में पूरे दिन बिक्री नहीं है',
  CHK_SLIP_READABLE: 'पर्ची साफ़ है',
  CHK_NAME_MATCHES_KYC: 'पर्ची का नाम आपके Paytm खाते से मेल खाता है',
  CHK_DATES_MATCH: 'पर्ची की तारीख़ें दुकान बंद रहने के दिनों को कवर करती हैं',
  CHK_WITHIN_AUTO_LIMIT: 'दिनों की संख्या अपने-आप भुगतान की सीमा के अंदर है',
  CHK_NOT_ALREADY_PAID: 'इन दिनों का भुगतान पहले नहीं हुआ',
  CHK_WITHIN_ANNUAL_LIMIT: 'आपकी साल की सीमा के अंदर',
  CF_TITLE: 'क्या बदलता तो नतीजा बदलता',
  CF_FOOTER: 'यह सिर्फ़ इस एक फ़ैसले का कारण बताता है। आगे की किसी घटना का फ़ैसला उस समय इन्हीं जाँचों से होगा।',
  'grv.step.PAYTM_DISPUTE': 'हमारा क्लेम अधिकारी',
  'grv.step.INSURER_GRO': 'बीमा कंपनी का शिकायत अधिकारी',
  'grv.step.BIMA_BHAROSA': 'IRDAI का बीमा भरोसा पोर्टल',
  'grv.step.OMBUDSMAN': 'बीमा लोकपाल',
  'grv.clock.own': 'हम {sla_hours} घंटे में जवाब देते हैं।',
  'grv.clock.confirm.insurer': 'जवाब का समय बीमा कंपनी से पूछकर तय होगा।',

  // Units of the numbers card (proposed)
  'explain.val.days': '{n} दिन',
  'explain.val.hours': '{n} घंटे',

  // The same lines in Hindi, quoted from the deck.
  DISPUTE_ACK: 'ठीक है, मैं इसे हमारी टीम को भेज रहा हूँ। 24 घंटे में जवाब मिलेगा।', // built catalogue line, quoted
  REASON_COVER_IN_FORCE: 'उस दिन आपका कवर चालू नहीं था।',
  REASON_PREMIUM_PREPAID: 'उस दिन का प्रीमियम पहले से जमा नहीं था।',
  REASON_SILENCE_VERIFIED: 'हमारे रिकॉर्ड में उस दिन दुकान पूरे दिन बंद नहीं दिखी।',
  REASON_NOT_ALREADY_PAID: 'उस दिन का भुगतान पहले ही हो चुका है।',
  REASON_WITHIN_ANNUAL_LIMIT: 'इससे साल की सीमा पार हो जाती।',
  REASON_COVER_BEFORE_ALERT: 'कवर अलर्ट जारी होने के बाद लिया गया था।',
  REASON_ALERT_ACTIVE: 'उस समय आपके इलाके में कोई मौसम अलर्ट नहीं था।',
  REASON_INDEX_QUORUM: 'आपके इलाके में हिसाब के लिए काफ़ी दुकानें नहीं थीं।',
  REASON_BELOW_FLOOR: 'आपके इलाके की बिक्री भुगतान की सीमा से नीचे नहीं गिरी।',
  REASON_BELOW_MODEL_RANGE: 'आपके इलाके की बिक्री आम दायरे के अंदर रही।',

  // The same line in Hindi, quoted from the deck.
  REASON_OFFICER_PERSONAL: 'पर्ची की जाँच के बाद यह दावा मंज़ूर नहीं हो सका।', // built catalogue line, quoted

  // Slip pre-check (N3, copy deck 12; the keys without a deck line are proposed and need the native review)
  SLIP_SHEET_TITLE: 'अस्पताल की पर्ची भेजें',
  SLIP_SHEET_HELP: 'भर्ती की पर्ची, छुट्टी का काग़ज़ या बिल की एक फ़ोटो लीजिए। रोशनी में, पूरा पन्ना दिखे।',
  SLIP_NOTICE: 'पर्ची की फ़ोटो पढ़ने के लिए किसी AI सेवा (Gemini या Sarvam) को भेजी जा सकती है। कृपया नमूना पर्ची भेजिए, असली नहीं।',
  SLIP_READING: 'पर्ची पढ़ी जा रही है…',
  SLIP_PRECHECK_SHOW: 'पर्ची पढ़ ली गई है। कृपया देख लीजिए, क्या यह सही है?',
  SLIP_FIELD_NAME: 'मरीज़ का नाम',
  SLIP_FIELD_ADMITTED: 'भर्ती की तारीख़',
  SLIP_FIELD_DISCHARGED: 'छुट्टी की तारीख़',
  SLIP_FIELD_HOSPITAL: 'अस्पताल',
  SLIP_FIELD_NOT_ON_SLIP: 'पर्ची पर नहीं है',
  SLIP_NOTE_NO_DISCHARGE: 'छुट्टी की तारीख़ पर्ची पर नहीं है। अगर आप अभी अस्पताल में हैं, तो यह सामान्य है।',
  SLIP_NOTE_NAME_NOT_LATIN: 'नाम अंग्रेज़ी अक्षरों में नहीं है, इसलिए हमारी टीम इसे देखेगी।',
  SLIP_CHECK_READABLE_PASS: 'फ़ोटो साफ़ पढ़ी जा सकी',
  SLIP_CHECK_READABLE_WARN: 'फ़ोटो साफ़ नहीं है',
  SLIP_CHECK_NAME_PASS: 'नाम पर्ची पर दिख रहा है',
  SLIP_CHECK_NAME_WARN: 'नाम साफ़ नहीं दिख रहा',
  SLIP_CHECK_DATES_PASS: 'भर्ती की तारीख़ पर्ची पर दिख रही है',
  SLIP_CHECK_DATES_WARN: 'भर्ती की तारीख़ साफ़ नहीं दिख रही',
  SLIP_ACTION_CONFIRM: 'हाँ, सही है',
  SLIP_ACTION_RETAKE: 'दूसरी फ़ोटो भेजें',
  SLIP_ACTION_TEAM: 'हमारी टीम को भेजें',
  SLIP_RETAKE_DOCUMENT: 'यह अस्पताल की पर्ची नहीं लग रही। कृपया भर्ती की पर्ची, छुट्टी का काग़ज़ या बिल की फ़ोटो भेजिए।',
  SLIP_RETAKE_CLEAR: 'फ़ोटो साफ़ नहीं है। रोशनी में, पर्ची सीधी रखकर, पूरी पर्ची की फ़ोटो भेजिए।',
  SLIP_RETAKE_NAME: 'मरीज़ का नाम साफ़ नहीं दिख रहा। नाम वाला हिस्सा पूरा दिखे, ऐसी फ़ोटो भेजिए।',
  SLIP_RETAKE_DATE: 'भर्ती की तारीख़ साफ़ नहीं दिख रही। तारीख़ वाला हिस्सा पूरा दिखे, ऐसी फ़ोटो भेजिए।',
  SLIP_NO_READ: 'अभी पर्ची पढ़ी नहीं जा सकी। आप इसे हमारी टीम को भेज सकते हैं, वे इसे देखेंगे।',
  SLIP_PHOTO_LIMIT: 'आप पहले भी फ़ोटो भेज चुके हैं। अब इसे हमारी टीम को भेज दीजिए।',
  SLIP_CONSENT_NEEDED: 'पर्ची पढ़ने से पहले हमें आपकी हामी चाहिए। ऐप खोलकर पर्ची वहीं भेजें। वह पहले आपकी हामी पूछेगा।',
  'slip.err.too_big': 'फ़ोटो बहुत बड़ी है। सीमा {max_mb} MB है।',
  'slip.err.bad_type': 'कृपया JPG, PNG या WebP फ़ोटो भेजिए।',
  'slip.err.damaged': 'यह फ़ोटो खुल नहीं सकी। कृपया दूसरी फ़ोटो चुनिए।',
  'slip.working': 'आपका दावा जाँचा जा रहा है…',
  'sim.slip': 'SIMULATED पर्ची पढ़ना। डेमो पर्चियों के लिए तय नतीजा इस्तेमाल होता है।',
  'slip.take_photo': 'फ़ोटो लें',
  'slip.choose_gallery': 'गैलरी से चुनें',
  'slip.cancel': 'रद्द करें',
  'slip.details': 'ब्योरा',
  'slip.details.provider': 'पढ़ने वाला: {provider}',
  'slip.details.model': 'मॉडल: {model}',
  'slip.details.reason': 'कारण: {reason}',
  'slip.what_read': 'जो हम पढ़ सके',
  'slip.not_clear': 'साफ़ नहीं',
  'slip.demo.title': 'डेमो पर्चियाँ',
  'slip.demo.good': 'डेमो पर्ची इस्तेमाल करें',
  'slip.demo.blurry': 'धुंधली डेमो पर्ची इस्तेमाल करें',
  'slip.help_row': 'अस्पताल की पर्ची भेजें',
  'slip.err.conflict': 'अभी पर्ची के लिए कोई खुला चेक-इन नहीं है, या दावा पहले ही भेजा जा चुका है।',
  'slip.none': 'अभी कुछ भेजना नहीं है। दुकान बंद रहने पर छतरी आपका हाल पूछता है, उसके बाद ही अस्पताल की पर्ची माँगता है।',
  'slip.none.home': 'होम पर जाएँ',
  'channel.label': 'छतरी के संदेश',
  'channel.hint': 'भुगतान, हाल-चाल और जवाब यहीं आते हैं। कवर और भुगतान वही रहते हैं।',
  'channel.linked': 'टेलीग्राम चैट जुड़ी है।',
  'channel.not_linked': 'अभी जुड़ा नहीं: टेलीग्राम में छतरी खोलें और स्टार्ट दबाएँ।',
  'channel.open': 'टेलीग्राम में छतरी खोलें',
  'channel.simulated': 'यहाँ टेलीग्राम सिम्युलेटेड है: संदेश कंसोल के फोन पर दिखते हैं।',
  'channel.error': 'बदल नहीं सका। फिर कोशिश करें।',
  'slip.err.limit': 'कई फ़ोटो भेजी जा चुकी हैं। कृपया पर्ची हमारी टीम को भेज दीजिए।',
  'grv.title': 'शिकायत और आगे के कदम',
  'grv.error.no_decision': 'आपके खाते में अभी कोई भुगतान या फ़ैसला नहीं है, इसलिए यहाँ शिकायत करने के लिए कुछ नहीं है। आपके दावों का ट्रैकर बताता है कि बात कहाँ तक पहुँची है।',
  'grv.error.no_review': 'आपका कोई दावा अभी समीक्षा के लिए रुका नहीं है।',
  'consent.title': 'मेरा डेटा और सहमति',
  'activity.title': 'क्या इस्तेमाल हुआ',
}
