/**
 * Marathi strings (card 6.7, flag `n8_marathi`). DRAFT: the copy-deck Marathi column and the lines written to match it
 * need a native speaker's review before the final (copy deck section 19). Plain Marathi in Devanagari, ASCII digits, no
 * nukta; loan words merchants use (कवर, प्रीमियम, KYC) stay. A key added later without Marathi falls back to Hindi
 * (lib/copy.ts), and the fallback text carries its own `lang`.
 */
import type { CopyKey } from './en'

export const mr: Readonly<Partial<Record<CopyKey, string>>> = {
  'nav.home': 'मुख्यपृष्ठ',
  'nav.claims': 'दावे',
  'nav.help': 'मदत',
  'app.name': 'छत्री',
  'app.tagline': 'Paytm for Business मधील छत्री',
  'app.clock': 'डेमोची तारीख आणि वेळ: {time}',
  'app.fullscreen': 'पूर्ण स्क्रीनवर उघडा',
  'clock.sheet.title': 'डेमोची तारीख आणि वेळ',
  'clock.sheet.note': 'डेमोचे घड्याळ पुढे-मागे करा. हा रिप्ले काल्पनिक आहे.',
  'clock.sheet.play': 'सुरू करा',
  'clock.sheet.pause': 'थांबवा',
  'clock.sheet.start': 'सुरुवातीला परत',
  'clock.chapter.alert': 'अलर्ट',
  'clock.chapter.trigger': 'ट्रिगर',
  'clock.chapter.paid': 'पेमेंट',
  'clock.chapter.instalment': 'हप्ता',
  'clock.chapter.checkin': 'विचारपूस',
  'clock.chapter.cover': 'कवर मागितले',
  'lang.label': 'भाषा',
  'lang.hi': 'हिंदी',
  'lang.en': 'English',
  'lang.mr': 'मराठी',
  'lang.fallback_note': 'काही मजकूर हिंदीत दाखवला आहे.',
  'settings.title': 'सेटिंग',
  'ask.title': 'छत्रीला विचारा',
  'home.title': 'आपले कवर',
  'explain.title': 'मला कोणत्या नुकसानीचे कवर मिळते?',
  'buy.title': 'कवर घ्या',
  'tracker.title': 'आपले दावे',
  'why.title': 'मला इतकीच रक्कम का मिळाली?',
  'receipt.title': 'आपल्या रकमेची पावती',
  'empty.claims': 'अजून कोणताही दावा नाही. हवामान अलर्ट दरम्यान आपल्या परिसरातील विक्री घटली, तर छत्री आपल्यासाठी दावा सुरू करते. आपल्या दुकानात दिवसभर विक्री झाली नाही, तर छत्री आपल्याला सर्व ठीक आहे का ते विचारेल.',
  'empty.cover': 'आपले अजून कोणतेही कवर नाही.',
  'empty.receipt': 'अजून पावती नाही. रक्कम जमा झाल्यानंतर पावती दिसते.',
  'error.title': 'हे लोड होऊ शकले नाही',
  'error.generic': 'काहीतरी चुकले. पुन्हा प्रयत्न करा.',
  'error.retry': 'पुन्हा प्रयत्न करा',
  'error.code': 'त्रुटी कोड: {code}',
  'error.network': 'सध्या कनेक्ट होत नाही. आपले इंटरनेट तपासा आणि पुन्हा प्रयत्न करा.',
  'error.timeout': 'यास खूप वेळ लागत आहे. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.',
  'error.not_found': 'हे सापडले नाही. ते काढून टाकले असू शकते, किंवा लिंक चुकीची असू शकते.',
  'offline.banner': 'ऑफलाइन. {time} चा डेटा दिसत आहे.',
  'offline.blocked': 'यासाठी इंटरनेट लागते. ऑनलाइन झाल्यावर पुन्हा प्रयत्न करा.',
  'offline.static': 'हा स्टॅटिक डेमो आहे. तो आपल्या ब्राउझरमध्ये बनावट डेटासह चालतो. काहीही कुठेही पाठवले जात नाही.',
  'explain.btn.got_it': 'समजले',
  'sim.banner': 'SIMULATED. हा डेमो डेटा आहे. खरे पैसे, संदेश किंवा पेमेंट जात नाही.',
  'app.frame_label': 'छतरी ॲप, SIMULATED',
  'app.tabs': 'मुख्य टॅब',
  'app.nba': 'पुढचे पाऊल',
  'app.back': 'मागे',
  'app.unknown_merchant': 'दुकानदार सापडला नाही',
  'state.loading': 'लोड होत आहे',
  'home.greeting': 'नमस्कार, {name} जी',
  'cover.status.pending_payment': 'पहिल्या पेमेंटची प्रतीक्षा',
  'cover.status.waiting': '{date} पासून सुरू होईल',
  'cover.status.active': 'सुरू',
  'cover.status.active_unpaid': 'सुरू, पुढील दिवसांचे प्रीमियम भरलेले नाही',
  'cover.status.lapsed': 'बंद',
  'cover.status.cancelled': 'रद्द',
  'home.row.zone': 'आपला परिसर',
  'home.row.premium_per_day': 'रोजचे प्रीमियम',
  'home.row.paid_through': 'या तारखेपर्यंत भरलेले',
  'home.row.starts_on': 'कवर सुरू',
  'home.row.instalment': 'रोजचा कर्जाचा हप्ता',
  'home.used': 'मागील {window_days} दिवसांत वापर: {used} / {limit}',
  'home.expected': 'आजची अपेक्षित विक्री',
  'home.latest': 'आपला ताजा दावा',
  'home.btn.coverage': 'मला कोणत्या नुकसानीचे कवर मिळते?',
  'home.btn.buy': 'कवर घ्या',
  'home.btn.claims': 'माझे दावे पहा',
  'home.btn.ask': 'छत्रीला विचारा',
  'home.alert.banner': 'अलर्ट {alert_id} · {valid_from} ते {valid_to}',
  'home.alert.covered': 'आपल्या परिसरासाठी हवामान अलर्ट सुरू आहे. छत्री आपल्या परिसरातील विक्रीवर लक्ष ठेवत आहे. आपल्याला काही करण्याची गरज नाही.',
  'home.alert.not_covered': 'आपल्या परिसरासाठी हवामान अलर्ट सुरू आहे. नवीन कवर वेटिंग पीरियडनंतर सुरू होते, म्हणून ते या अलर्टसाठी लागू होणार नाही.',
  'alert.id': 'अलर्ट {alert_id}',
  'explain.numbers.title': 'आपले कवर, आकड्यांत',
  'explain.num.share': 'गमावलेल्या विक्रीतील छत्रीचा वाटा',
  'explain.num.area_cap': 'रोजची मर्यादा, पाऊस',
  'explain.num.personal_cap': 'रोजची मर्यादा, रुग्णालय',
  'explain.num.annual': 'वार्षिक मर्यादा',
  'explain.num.waiting': 'वेटिंग पीरियड',
  'explain.num.lookahead': 'इतक्या तास पुढेपर्यंत अलर्ट पाहिले जातात',
  'explain.num.first_days': 'पहिले पेमेंट इतक्या दिवसांसाठी',
  'explain.c2.title': 'पावसामुळे विक्रीचे नुकसान',
  'explain.c2.body': 'हवामान अलर्ट सुरू असताना आपल्या परिसरातील विक्री सलग {hours} तास नेहमीच्या पातळीच्या {floor_pct}% पेक्षा खाली राहिली, आणि घट नेहमीच्या मंद दिवसापेक्षा जास्त असली, तर छत्री आपल्या दुकानाच्या गमावलेल्या विक्रीच्या {share_pct}% रक्कम देते. हा हिशोब आपला नेहमीचा दिवस आणि परिसरातील घट यावरून ठरतो. दिवसाला जास्तीत जास्त {area_cap}. आपल्याला दावा करावा लागत नाही.',
  'explain.c2.example': 'एका चहाच्या दुकानाची मंगळवारी साधारण ₹4,380 विक्री होते. एका पावसाळी मंगळवारी परिसरातील विक्री 63% घटली. गमावलेल्या विक्रीची निम्मी रक्कम ₹1,379.70 आहे, जी ₹1,380 होते, म्हणून दुकानाला ₹1,380 मिळाले.',
  'explain.c3.title': 'रुग्णालयात असताना उत्पन्नाचे नुकसान',
  'explain.c3.body': 'आपल्या दुकानात पूर्ण दिवस विक्री झाली नाही, तर छत्री आपल्याला सर्व ठीक आहे का ते विचारते. आपण रुग्णालयात असाल, तर रुग्णालयाच्या पर्चीचा एक फोटो पाठवा. पर्ची तपासणीत बरोबर निघाली, तर छत्री आपल्या नेहमीच्या दिवसाच्या {share_pct}% रक्कम देते, दिवसाला जास्तीत जास्त {personal_cap}, आणि जास्तीत जास्त {max_auto_days} दिवसांपर्यंत. त्यापेक्षा जास्त दिवसांचा दावा एक व्यक्ती तपासते.',
  'explain.c3.example': 'एका दुकानाची बुधवारी साधारण ₹4,300 विक्री होते. मालक रुग्णालयात होते आणि त्या दिवशी दुकानात विक्री झाली नाही. ₹4,300 चे निम्मे ₹2,150 आहे, पण दिवसाची मर्यादा ₹1,500 आहे, म्हणून त्या दिवसाचे ₹1,500 दिले गेले.',
  'explain.c4.title': 'छत्री किती रक्कम देते',
  'explain.c4.body': 'छत्री आपल्या गमावलेल्या विक्रीच्या {share_pct}% रक्कम देते. एका दिवसासाठी जास्तीत जास्त पावसासाठी {area_cap} आणि रुग्णालयासाठी {personal_cap}. रुग्णालयाची रक्कम पुनरावलोकनाशिवाय जास्तीत जास्त {max_auto_days} दिवसांपर्यंत दिली जाते. कोणत्याही {window_days} दिवसांत सर्व रक्कम जोडल्यावर {annual_limit} पेक्षा जास्त होत नाही.',
  'explain.c5.title': 'कवर केव्हा सुरू होते',
  'explain.c5.body': 'नवीन कवर मागितल्यानंतर {waiting_days} दिवसांनी सुरू होते. आपल्या परिसरासाठी अलर्ट सुरू असेल, किंवा जाहीर झाला असेल आणि {lookahead_hours} तासांत सुरू होणार असेल, तर कवर लगेच सुरू होऊ शकत नाही. पुढील काळासाठी कवर आपण तरीही घेऊ शकता. अलर्ट जाहीर झाल्यानंतर घेतलेले कवर त्या अलर्टसाठी कधीही रक्कम देत नाही.',
  'explain.c5.example': 'रमेश सोमवारी 18 ऑगस्टला 18:00 वाजता कवर मागतात. त्यांचे कवर 25 ऑगस्टपासून सुरू होते.',
  'explain.c6.title': 'प्रीमियम आणि आधी भरलेले दिवस',
  'explain.c6.body': 'पहिले पेमेंट {first_days} दिवसांसाठी असते. त्यानंतर संध्याकाळचे सेटलमेंट आपल्या कायम संमतीने पुढील दिवसाचे प्रीमियम कापते. ज्या दिवसांचे प्रीमियम आधी भरलेले असते त्याच दिवसांना कवर लागू होते.',
  'explain.c6.example': 'डेमोमध्ये झोन 3 चे प्रीमियम रोज ₹14.16 आहे, म्हणून 30 दिवसांचे ₹424.80 होतात. खरी किंमत अजून ठरलेली नाही.',
  'explain.c7.title': 'दाव्याची रक्कम केव्हा दिली जात नाही',
  'explain.c7.body': 'एखादी आवश्यक तपासणी यशस्वी झाली नाही, तर दाव्याची रक्कम दिली जात नाही. खाली छत्री जी कारणे सांगते ती आहेत. ज्या गोष्टीबद्दल सिस्टमला खात्री नसते ती एक व्यक्ती तपासते. हा नकार नाही.',
  'explain.c10.title': 'आपला कर्जाचा हप्ता',
  'explain.c10.body': 'रक्कम दिल्यानंतर छत्री आपल्या लेंडरला आपला पुढचा हप्ता थांबवण्यास सांगते. निर्णय लेंडरचा असतो, छत्रीचा नाही.',
  'explain.example.title': 'उदाहरण',
  'explain.example.sim': 'SIMULATED रीप्लेचे उदाहरण',
  'explain.price.covered': 'आपली किंमत: {per_day} प्रतिदिन.',
  'explain.price.uncovered': 'कवर घ्या वर टॅप केल्यावर आपल्याला आपली किंमत दिसेल.',
  'explain.price.prototype': 'प्रोटोटाइपची किंमत. खरी किंमत अजून ठरलेली नाही.',
  'explain.no_forms': 'पावसाच्या दाव्यासाठी फॉर्म नको. रुग्णालयाच्या दाव्यासाठी पर्चीचा एक फोटो लागतो.',
  'explain.rules_note': 'हे डेमो नियम आहेत ({rules_version}). ते फक्त उदाहरणासाठी आहेत. खरे नियम भागीदार विमा कंपनी ठरवेल.',
  'explain.terms_hint': 'अधोरेखित शब्दावर टॅप करा, त्याचा अर्थ दिसेल.',
  'reason.cover_in_force': 'त्या दिवशी तुमचे कवर चालू नव्हते.',
  'reason.premium_prepaid': 'त्या दिवसाचा प्रीमियम आधी भरलेला नव्हता.',
  'reason.silence_verified': 'आमच्या नोंदींनुसार त्या दिवशी दुकान पूर्ण दिवस बंद दिसले नाही.',
  'reason.not_already_paid': 'त्या दिवसाचे पेमेंट आधीच झाले आहे.',
  'reason.within_annual_limit': 'यामुळे वर्षाची मर्यादा ओलांडली गेली असती.',
  'reason.cover_before_alert': 'अलर्ट जारी झाल्यानंतर कवर घेतले होते.',
  'reason.alert_active': 'त्या वेळी तुमच्या परिसरात हवामान अलर्ट नव्हता.',
  'reason.index_quorum': 'तुमच्या परिसरात हिशोबासाठी पुरेशी दुकाने नव्हती.',
  'reason.below_floor': 'तुमच्या परिसरातील विक्री पेमेंटच्या मर्यादेखाली गेली नाही.',
  'reason.below_model_range': 'तुमच्या परिसरातील विक्री नेहमीच्या मर्यादेत राहिली.',
  'buy.intro': 'नवीन कवर नेहमी मागितल्यानंतर {waiting_days} दिवसांनी सुरू होते.',
  'buy.check': 'किंमत आणि सुरू होण्याची तारीख पहा',
  'buy.outcome.ok': 'कवर {date} पासून सुरू होईल',
  'buy.outcome.blocked': 'सध्या थांबले आहे. कवर {date} पासून सुरू होईल.',
  'buy.row.starts': 'कवर सुरू',
  'buy.row.per_day': 'रोजचे प्रीमियम',
  'buy.row.first_payment': 'पहिले पेमेंट ({first_days} दिवस)',
  'buy.blocked_note': 'अलर्ट जाहीर झाल्यानंतर घेतलेले कवर त्या अलर्टसाठी रक्कम देत नाही. पुढील काळासाठी कवर आपण तरीही घेऊ शकता.',
  'buy.consent.notice': 'छत्री आपला विक्रीचा डेटा दावे ठरवण्यासाठी आणि आपले प्रीमियम ठरवण्यासाठी वापरते.',
  'buy.consent.text': 'पैसे भरण्यापूर्वी: छत्री आपल्या विक्रीच्या डेटावरून दावे ठरवते आणि प्रीमियम ठरवते. पहिल्या पेमेंटनंतर छत्री आपल्या रोजच्या सेटलमेंटमधून पुढच्या दिवसाचे प्रीमियम घेते. आपण रुग्णालयाची पर्ची पाठवल्यास छत्री ती वाचते, फक्त त्या दाव्यासाठी. यापैकी प्रत्येक गोष्ट आपण ॲपमध्ये मदत, माझा डेटा आणि संमती येथे बंद करू शकता. हा प्रोटोटाइप आहे आणि यातील डेटा सिम्युलेटेड आहे.',
  'buy.consent.version': 'सूचना आवृत्ती {version}',
  'buy.consent.box.SALES_DATA_FOR_CLAIM': 'मी सहमत आहे: छत्री माझ्या विक्रीचा डेटा दावे ठरवण्यासाठी आणि प्रीमियम ठरवण्यासाठी वापरू शकते.',
  'buy.consent.box.SETTLEMENT_DEDUCTION': 'मी सहमत आहे: पहिल्या पेमेंटनंतर छत्री माझ्या रोजच्या सेटलमेंटमधून पुढच्या दिवसाचे प्रीमियम घेऊ शकते.',
  'buy.consent.box.SLIP_DATA_FOR_HOSPITAL_CLAIM': 'मी सहमत आहे: मी रुग्णालयाची पर्ची पाठवली, तर छत्री ती वाचू शकते.',
  'buy.consent.tag.required': 'कवरसाठी आवश्यक',
  'buy.consent.tag.optional': 'ऐच्छिक',
  'buy.consent.hint': 'पुढे जाण्यासाठी “कवरसाठी आवश्यक” असे लिहिलेले दोन्ही बॉक्स निवडा.',
  'buy.consent.error': 'सूचना बदलली आहे. कृपया ती पुन्हा वाचा.',
  'buy.pay': 'Paytm ने पेमेंट करा',
  'buy.simulate': 'पेमेंटचे सिम्युलेशन करा',
  'buy.pending': 'आपल्या पेमेंटची प्रतीक्षा आहे. पेमेंट येताच हे पान बदलेल.',
  'buy.link.simulated': 'SIMULATED पेमेंट लिंक. खरे पैसे जात नाहीत.',
  'buy.paid': 'पेमेंट मिळाले.',
  'buy.link_label': 'पेमेंट लिंक',
  'buy.link_unavailable': 'पेमेंट लिंक आत्ता तयार झाली नाही. थोड्या वेळाने पुन्हा विचारा.',
  'buy.needs_presenter': 'या डेमो कामासाठी प्रेझेंटरचे सेशन लागते.',
  'error.pay_failed': 'पेमेंट होऊ शकले नाही. कोणतेही पैसे कापले गेले नाहीत. आपण पुन्हा प्रयत्न करू शकता.',
  'help.about.title': 'या प्रोटोटाइपबद्दल',
  'help.about.text': 'हा एक प्रोटोटाइप आहे. अनिल जाधव यांच्यासह येथील सर्व दुकानदार काल्पनिक आहेत. SIMULATED लिहिलेली प्रत्येक गोष्ट खरी नाही: विक्री, अलर्ट, KYC, रक्कम, लेंडर, Soundbox, WhatsApp आणि Paytm लिंक.',
  'origin.LIVE.hint': 'हे खऱ्या कनेक्शनमधून आले आहे.',
  'origin.SIMULATED.hint': 'डेमो डेटा. खरे पैसे, संदेश किंवा पेमेंट जात नाही.',
  'mode.FALLBACK.hint': 'नेहमीची सेवा उपलब्ध नव्हती, म्हणून बॅकअप वापरले जात आहे.',
  'help.glossary.title': 'विम्याचे शब्द, सोप्या भाषेत',
  'help.dispute.hint': 'एखादी रक्कम चुकीची वाटली, तर दावा उघडा आणि “हे चुकीचे आहे” दाबा.',
  'lang.preview': 'पूर्वावलोकन',
  'lang.native_hint': 'प्रत्येक भाषा तिच्या स्वतःच्या लिपीत दाखवली आहे.',
  'lens.title': 'या शब्दाचा अर्थ काय?',
  'lens.plain': 'सोप्या शब्दांत',
  'lens.example': 'उदाहरण',
  'lens.close': 'बंद करा',
  'lens.footer': 'हे शब्द सोप्या भाषेत समजावते. नेमक्या अटी पॉलिसीच्या शब्दांत आहेत.',
  'jargon.waiting_period.term': 'वेटिंग पीरियड',
  'jargon.waiting_period.what': 'नवीन कवर मागितल्यानंतर {waiting_days} दिवसांनी सुरू होते. तोपर्यंत ते रक्कम देत नाही.',
  'jargon.waiting_period.example': 'रमेश सोमवारी 18 ऑगस्टला कवर मागतात. त्यांचे कवर 25 ऑगस्टपासून सुरू होते.',
  'jargon.alert.term': 'हवामान अलर्ट',
  'jargon.alert.what': 'आपल्या परिसरासाठी हवामानाचा इशारा. अलर्ट जाहीर झाल्यानंतर घेतलेले कवर त्या अलर्टसाठी रक्कम देत नाही.',
  'jargon.alert.example': 'अलर्ट A-20250818-01 सोमवारी 18 ऑगस्टला 17:30 वाजता पुढील दिवसासाठी जाहीर झाला होता.',
  'jargon.expected_day.term': 'आपला नेहमीचा दिवस',
  'jargon.expected_day.what': 'आठवड्याच्या या दिवशी छत्रीच्या हिशोबाने आपल्या दुकानाची साधारण विक्री, जी आपल्या मागील विक्रीवरून काढली जाते.',
  'jargon.expected_day.example': 'अनिल यांचा नेहमीचा मंगळवार: ₹4,380.',
  'jargon.area_drop.term': 'परिसरातील घट',
  'jargon.area_drop.what': 'आपल्या परिसरातील दुकानांची विक्री अपेक्षेपेक्षा किती टक्के घटली.',
  'jargon.area_drop.example': '19 ऑगस्टला झोन 7 अपेक्षेच्या 37% राहिला, म्हणजे 63% घट.',
  'jargon.payout_share.term': 'छत्रीचा वाटा',
  'jargon.payout_share.what': 'छत्री आपल्या गमावलेल्या विक्रीच्या {share_pct}% रक्कम देते.',
  'jargon.payout_share.example': '½ × ₹4,380 × 63% = ₹1,380: निम्मे × आपला नेहमीचा दिवस × परिसरातील घट.',
  'jargon.daily_cap.term': 'रोजची मर्यादा',
  'jargon.daily_cap.what': 'एका दिवसासाठी छत्री जास्तीत जास्त जितकी रक्कम देते: पावसासाठी {area_cap} आणि रुग्णालयासाठी {personal_cap}.',
  'jargon.daily_cap.example': '₹4,300 च्या दिवसाचे निम्मे ₹2,150 आहे, पण रुग्णालयाची रोजची मर्यादा ₹1,500 आहे, म्हणून ₹1,500 दिले जातात.',
  'jargon.annual_limit.term': 'वार्षिक मर्यादा',
  'jargon.annual_limit.what': 'कोणत्याही {window_days} दिवसांत छत्री आपल्याला जास्तीत जास्त जितकी रक्कम देते: {annual_limit}.',
  'jargon.annual_limit.example': 'जो दावा आपल्याला मर्यादेच्या वर नेईल, त्याची रक्कम दिली जात नाही.',
  'jargon.premium.term': 'प्रीमियम',
  'jargon.premium.what': 'कवरसाठी आपण दररोज भरत असलेली थोडी रक्कम.',
  'jargon.premium.example': 'डेमोमध्ये झोन 3 चे प्रीमियम रोज ₹14.16 आहे, म्हणून 30 दिवसांचे ₹424.80. खरी किंमत अजून ठरलेली नाही.',
  'jargon.prepaid_through.term': 'या तारखेपर्यंत भरलेले',
  'jargon.prepaid_through.what': 'ज्या दिवसांचे प्रीमियम आधी भरलेले असते त्या दिवसांना कवर लागू होते. हा शेवटचा भरलेला दिवस आहे.',
  'jargon.prepaid_through.example': 'रमेश यांच्या ₹424.80 मधून 30 दिवसांचे प्रीमियम भरले जाते, 25 ऑगस्ट ते 23 सप्टेंबर.',
  'jargon.settlement.term': 'सेटलमेंट',
  'jargon.settlement.what': 'आपल्या Paytm विक्रीचे आपल्या बँक खात्यात जाणे.',
  'jargon.settlement.example': 'अनिल यांचे ₹1,380 17:04 वाजता सेटलमेंटसोबत आले (SIMULATED).',
  'jargon.edi_holiday.term': 'हप्त्याची सुट्टी (EDI)',
  'jargon.edi_holiday.what': 'आपण आपले कर्ज रोजच्या हप्त्याने (EDI) फेडत असाल, तर आपला लेंडर एका दिवसाचा हप्ता थांबवू शकतो. निर्णय लेंडरचा असतो, छत्रीचा नाही.',
  'jargon.edi_holiday.example': 'अनिल यांचा ₹600 चा हप्ता: छत्री विचारते, लेंडर उत्तर देतो.',
  'jargon.kyc.term': 'KYC',
  'jargon.kyc.what': 'आपल्याबद्दल Paytm कडे आधीपासून असलेली ओळखीची माहिती, उदाहरणार्थ आपले नाव.',
  'jargon.kyc.example': 'रुग्णालयाच्या पर्चीवरील नावाची आपल्या KYC नावाशी तुलना केली जाते. {name_match_min} किंवा त्यापेक्षा जास्त गुण असतील तर नाव जुळते.',
  'jargon.referred.term': 'आमची टीम पाहत आहे',
  'jargon.referred.what': 'आमच्या टीममधील एक व्यक्ती निर्णय घेईल. हा नकार नाही. {sla_hours} तासांत उत्तर मिळेल.',
  'jargon.referred.example': 'पर्चीवरील "सुनील पवार" हे नाव KYC शी जुळले नाही, म्हणून केस C-2291 अधिकाऱ्याकडे गेला.',
  'jargon.audit_fingerprint.term': 'ऑडिट कोड',
  'jargon.audit_fingerprint.what': 'प्रत्येक निर्णय जोडलेल्या कड्यांच्या लॉगमध्ये लिहिला जातो. जुनी ओळ बदलली तर साखळी तुटते. हा कोड या निर्णयाच्या ओळीची ओळख आहे.',
  'jargon.audit_fingerprint.example': '"लॉग तपासा" सांगते की संपूर्ण लॉग अखंड आहे की नाही.',
  'jargon.rules_version.term': 'नियमांची आवृत्ती',
  'jargon.rules_version.what': 'या निर्णयात वापरलेल्या नियमांची आवृत्ती.',
  'jargon.rules_version.example': 'उदाहरण: {rules_version}.',
  'nba.get_cover_from_coverage': 'कवर घ्यायचे आहे? किंमत आणि सुरू होण्याची तारीख पहा.',
  'nba.get_cover_from_coverage.btn': 'कवर घ्या',
  'nba.see_claims': 'छत्रीने आपल्यासाठी काय केले ते पहा.',
  'nba.see_claims.btn': 'माझे दावे पहा',
  'nba.home_from_coverage': 'कवरबद्दल एवढेच.',
  'nba.home_from_coverage.btn': 'मुख्यपृष्ठावर परत',
  'nba.check_price': 'आधी आपली किंमत आणि सुरू होण्याची तारीख पहा.',
  'nba.check_price.btn': 'किंमत आणि सुरू होण्याची तारीख पहा',
  'nba.pay': 'कवर सुरू करण्यासाठी पहिले पेमेंट करा.',
  'nba.pay.btn': 'Paytm ने पेमेंट करा',
  'nba.home_after_paid': 'पेमेंट मिळाले.',
  'nba.home_after_paid.btn': 'मुख्यपृष्ठावर परत',
  'nba.home_when_covered': 'आपल्याकडे आधीपासून कवर आहे.',
  'nba.home_when_covered.btn': 'मुख्यपृष्ठावर परत',
  'nba.open_latest': 'प्रत्येक टप्पा पाहण्यासाठी आपला ताजा दावा उघडा.',
  'nba.open_latest.btn': 'ताजा दावा उघडा',
  'nba.see_coverage_empty': 'अजून कोणताही दावा नाही. काय कवर आहे ते पहा.',
  'nba.see_coverage_empty.btn': 'काय कवर आहे ते पहा',
  'nba.wait_for_officer': 'क्लेम अधिकारी हे पाहत आहेत. {sla_hours} तासांत उत्तर मिळेल.',
  'nba.wait_for_officer.btn': 'दाव्यांकडे परत',
  'nba.see_why': 'आपले {amount} जमा झाले आहेत. हिशोब कसा झाला ते पहा.',
  'nba.see_why.btn': 'इतकी रक्कम का?',
  'nba.back_to_claims': 'या दाव्याबद्दल एवढेच.',
  'nba.back_to_claims.btn': 'दाव्यांकडे परत',
  'nba.see_receipt': 'या निर्णयाची पावती आपल्याजवळ ठेवा.',
  'nba.see_receipt.btn': 'पावती पहा',
  'nba.disagree': 'सहमत नाही का? आम्हाला सांगा.',
  'nba.disagree.btn': 'हे चुकीचे आहे',
  'nba.home_after_language': 'भाषा सेव्ह झाली.',
  'nba.home_after_language.btn': 'मुख्यपृष्ठावर परत',
  'nba.see_dispute_case': 'आपला केस क्लेम अधिकाऱ्याकडे आहे. {sla_hours} तासांत उत्तर मिळेल.',
  'nba.see_dispute_case.btn': 'माझा केस पहा',
  'nba.see_referred_claim': 'क्लेम अधिकारी आपला दावा तपासत आहेत.',
  'nba.see_referred_claim.btn': 'माझा दावा पहा',
  'nba.see_coverage_waiting': 'आपले कवर {starts_on} पासून सुरू होईल.',
  'nba.see_coverage_waiting.btn': 'काय कवर आहे ते पहा',
  'nba.get_cover': 'आपल्याकडे अजून कवर नाही.',
  'nba.get_cover.btn': 'कवर घ्या',
  'nba.see_premium': 'पुढील दिवसांचे प्रीमियम भरलेले नाही. हे कसे चालते ते पहा.',
  'nba.see_premium.btn': 'हे कसे चालते ते पहा',
  'nba.alert_notice': 'आपल्या परिसरासाठी अलर्ट आहे. परिसरातील विक्री घटली, तर छत्री आपोआप आकडे तपासते.',
  'nba.alert_notice.btn': 'काय कवर आहे ते पहा',
  'nba.see_coverage': 'आपल्याला कोणत्या नुकसानीचे कवर मिळते ते पहा.',
  'nba.see_coverage.btn': 'काय कवर आहे ते पहा',
  'nba.tick_consent': 'पुढे जाण्यासाठी “कवरसाठी आवश्यक” असे लिहिलेले बॉक्स निवडा.',
  'nba.tick_consent.btn': 'बॉक्सकडे जा',
  'nba.send_slip': 'आपल्या रुग्णालयाच्या पर्चीचा एक फोटो पाठवा.',
  'nba.send_slip.btn': 'पर्चीचा फोटो पाठवा',
  'nba.ask': 'काही प्रश्न आहे का? छत्रीला विचारा.',
  'nba.ask.btn': 'छत्रीला विचारा',
  'tracker.kind.area': 'पावसामुळे विक्रीचे नुकसान',
  'tracker.kind.personal': 'रुग्णालयात असताना उत्पन्नाचे नुकसान',
  'tracker.kind.dispute': 'रकमेबद्दल प्रश्न',
  'tracker.state.now': 'सुरू आहे',
  'claim.status.approved_pending': 'मंजूर. रक्कम येत आहे.',
  'claim.status.paid': 'रक्कम दिली गेली',
  'claim.status.referred': 'आमची टीम पाहत आहे',
  'claim.status.declined': 'रक्कम दिली गेली नाही',
  'claim.status.waiting_slip': 'आपल्या पर्चीची प्रतीक्षा',
  'claim.status.question_open': 'प्रश्न खुला आहे',
  'claim.status.question_closed': 'प्रश्न बंद. रक्कम तीच राहिली.',
  'tracker.step.detected': 'आढळले',
  'tracker.step.checked': 'तपासले',
  'tracker.step.decided': 'निर्णय झाला',
  'tracker.step.paid': 'जमा झाले',
  'tracker.step.edi': 'हप्त्याची सुट्टी (EDI)',
  'tracker.state.done': 'झाले',
  'tracker.state.waiting': 'प्रतीक्षा',
  'tracker.state.na': 'गरज नाही',
  'tracker.state.stopped': 'येथे थांबले',
  'tracker.clock.left': '{hours} तास बाकी',
  'tracker.clock.due': 'उत्तराची वेळ: {time} पर्यंत',
  'tracker.clock.overdue': 'वेळमर्यादा उलटली',
  'tracker.btn.receipt': 'पावती पहा',
  'tracker.btn.wrong': 'हे चुकीचे आहे',
  'tracker.btn.why': 'इतकी रक्कम का?',
  'tracker.next.referred': 'पुढे: एक व्यक्ती निर्णय घेईल. {sla_hours} तासांत उत्तर मिळेल.',
  'tracker.next.after_decided': 'पुढे: पैसे सेटलमेंटसोबत जमा होतात.',
  'tracker.next.after_paid': 'पुढे: आपले कर्ज असल्यास हप्त्याबद्दल लेंडर निर्णय घेतो.',
  'tracker.next.done': 'सर्व टप्पे पूर्ण झाले. आपली पावती तयार आहे.',
  'tracker.next.declined': 'आपण कारण विचारू शकता किंवा आमच्या टीमशी बोलू शकता.',
  'why.numbers': 'आपले आकडे',
  'why.no_amount': 'अजून कोणतीही रक्कम नाही. एक व्यक्ती आपला दावा तपासत आहे.',
  'TRACK_CHECKED_OK': 'सर्व {passed} तपासण्या यशस्वी झाल्या.',
  'TRACK_CHECKED_FAILED': 'एक आवश्यक तपासणी यशस्वी झाली नाही.',
  'TRACK_REFERRED_UNREADABLE': 'पर्ची स्पष्ट वाचता आली नाही.',
  'TRACK_REFERRED_NAME': 'पर्चीवरील नाव आपल्या KYC शी जुळत नाही.',
  'TRACK_REFERRED_DATES': 'पर्चीवरील तारखा दुकान बंद असलेल्या दिवसांशी जुळत नाहीत.',
  'TRACK_REFERRED_DAYS': 'हा दावा आपोआप भरपाई देण्याच्या दिवसांपेक्षा जास्त दिवसांचा आहे.',
  'TRACK_DECIDED_AUTO': 'मंजूर {amount}',
  'TRACK_DECIDED_OFFICER': 'क्लेम अधिकाऱ्याने मंजूर केले',
  'TRACK_PAID_PENDING': '{amount} पुढील सेटलमेंटसोबत येत आहे.',
  'TRACK_PAID_ETA': 'सुमारे {minutes} मिनिटांत जमा होईल (डेमो घड्याळ).',
  'TRACK_PAID_FAILED': 'रक्कम जमा होऊ शकली नाही. कृपया आमच्या टीमशी बोला.',
  'TRACK_EDI_REQUESTED': 'आम्ही आपल्या लेंडरला सांगितले आहे. निर्णय लेंडरचा असतो.',
  'TRACK_EDI_REFUSED': 'उपलब्ध नाही. आपला हप्ता नेहमीप्रमाणे देय आहे.',
  'TRACK_EDI_NO_RESPONSE': 'आम्ही आपल्या लेंडरपर्यंत पोहोचू शकलो नाही. आपला हप्ता नेहमीप्रमाणे देय आहे.',
  'TRACK_EDI_NONE': 'कोणतेही कर्ज नोंदलेले नाही',
  'TRACK_DISPUTE_OPEN': 'प्रश्न खुला आहे · केस {case_id}. {sla_hours} तासांत उत्तर मिळेल.',
  'TRACK_DISPUTE_CLOSED': 'आमच्या टीमने तपासले. दिलेली रक्कम {amount} तीच राहील.',
  'CASE_CHIP': 'क्लेम अधिकाऱ्याकडे पाठवला · केस {case_id}',
  'sim.payment': 'SIMULATED पेमेंट. खरे पैसे जात नाहीत.',
  'sim.lender': 'SIMULATED लेंडर. उत्तर डेमो नियमांवरून येते.',
  'tracker.steps_label': 'दाव्याचे टप्पे',
  'tracker.live_step': '{step}: {state}',
  'tracker.about_claim': 'दावा {claim_id} बद्दल',
  'tracker.officer_note': 'आमच्या टीमची नोंद',
  'why.row.expected_day': 'तुमचा नेहमीचा दिवस',
  'why.row.area_index': 'परिसराचा इंडेक्स',
  'why.row.area_drop': 'परिसरातील घट',
  'why.row.days': 'दाव्याचे दिवस',
  'why.row.share': 'छतरीचा वाटा',
  'why.row.cap': 'रोजची मर्यादा',
  'why.row.amount': 'तुमचे पेमेंट',
  'why.value.half': 'निम्मे',
  'why.person_heading': 'कोणी व्यक्ती का तपासत आहे',
  'receipt.title.record': 'आपल्या निर्णयाची नोंद',
  'receipt.row.decision': 'निर्णय',
  'receipt.row.rules': 'नियमांची आवृत्ती',
  'receipt.row.decided_at': 'निर्णयाची वेळ',
  'receipt.row.decided_by': 'निर्णय कोणी घेतला',
  'receipt.row.formula': 'हिशोब कसा झाला',
  'receipt.row.sources': 'प्रत्येक आकडा कुठून आला',
  'receipt.row.checks': 'तपासण्या',
  'receipt.row.paid_at': 'जमा झाले',
  'receipt.row.pending': 'जमा होणे बाकी',
  'receipt.row.audit': 'ऑडिट नोंद (पहिली {n} अक्षरे)',
  'receipt.row.what_changes': 'काय बदलले असते तर निकाल बदलला असता',
  'receipt.row.disagree': 'आपण सहमत नसल्यास',
  'receipt.row.payout': 'रक्कम',
  'receipt.row.lender': 'लेंडरचे उत्तर',
  'receipt.row.clauses': 'वापरलेली पॉलिसी कलमे',
  'receipt.by.engine': 'नियमांची आपोआप तपासणी (कोड, AI नाही)',
  'receipt.by.officer': 'क्लेम अधिकारी',
  'receipt.btn.print': 'प्रिंट करा किंवा PDF बनवा',
  'receipt.check_log': 'लॉग तपासा',
  'receipt.log.ok': 'लॉग अखंड आहे, {entries} नोंदी',
  'receipt.log.broken': 'लॉग नोंद {seq} वर तुटलेला आहे.',
  'receipt.print.header': 'छत्री · निर्णयाची पावती · प्रोटोटाइप · SIMULATED डेटा',
  'receipt.simulated': 'SIMULATED पावती. डेटा आणि रक्कम खरी नाही.',
  'receipt.footer': 'ही पावती एका निर्णयाचे स्पष्टीकरण देते. हा पॉलिसीचा दस्तऐवज नाही.',
  'receipt.checks.show': 'तपासण्या दाखवा',
  'receipt.checks.hide': 'तपासण्या लपवा',
  'receipt.check.observed': 'आम्हाला काय मिळाले',
  'receipt.check.required': 'काय आवश्यक होते',
  'receipt.lender.granted': 'तुमच्या लेंडरने {date} रोजीचा {instalment} चा हप्ता थांबवला आहे. तो तुमच्या कर्जाच्या शेवटी जातो, कोणताही दंड नाही.',
  'src.RULES': 'छत्रीचे नियम {rules_version}',
  'src.CLAUSE': 'पॉलिसीचे कलम {clause}',
  'src.ALERT': 'हवामान अलर्ट {alert_id}',
  'src.SALES_INDEX': 'परिसरातील विक्रीचा हिशोब',
  'src.FORECAST': 'आपला नेहमीचा दिवस, आपल्या मागील विक्रीवरून काढलेला',
  'src.ZONE_BOUND': 'आपल्या परिसराची नेहमीची श्रेणी',
  'src.COVER': 'आपल्या कवरची नोंद',
  'src.PREMIUM': 'आपले प्रीमियम पेमेंट',
  'src.KYC': 'आपल्या Paytm खात्यावरील नाव (KYC)',
  'src.SLIP': 'रुग्णालयाची पर्ची, जशी वाचली गेली',
  'src.SALES_DAY': 'त्या दिवसाची आपली विक्री',
  'src.PAYOUT_HISTORY': 'आपल्याला आधी मिळालेली रक्कम',
  'src.LENDER': 'लेंडरचे उत्तर',
  'chip.tap': 'हे कुठून आले ते पाहण्यासाठी टॅप करा.',
  'badge.source_missing': 'स्रोत सापडला नाही',
  'chip.field.record': 'नोंद',
  'chip.field.time': 'वेळ',
  'chip.field.origin': 'स्रोताचा प्रकार',
  'chip.field.clause': 'पॉलिसीचे कलम',
  'origin.CONFIG.hint': 'ही छत्रीसोबत येणारी निश्चित सेटिंग किंवा कागदपत्र आहे.',
  'source.close': 'बंद करा',
  'source.sheet_desc': 'ही किंमत कुठून आली.',
  'clause.C1': 'वापरलेले शब्द',
  'clause.C2': 'पावसामुळे विक्रीचे नुकसान',
  'clause.C3': 'रुग्णालयात असताना उत्पन्नाचे नुकसान',
  'clause.C4': 'किती रक्कम मिळते',
  'clause.C5': 'कवर केव्हा सुरू होते',
  'clause.C6': 'प्रीमियम आणि आधी पेमेंट',
  'clause.C7': 'काय कवर नाही',
  'clause.C8': 'दावे कसे ठरतात',
  'clause.C9': 'प्रश्न आणि तक्रारी',
  'clause.C10': 'हप्त्याची सुट्टी: लेंडर ठरवतो',
  'clause.C11': 'आपला डेटा आणि संमती',
  'clause.C12': 'रद्द करणे आणि नूतनीकरण',
  'chk.status.PASS': 'यशस्वी',
  'chk.status.FAIL': 'पूर्ण झाले नाही',
  'chk.status.UNSURE': 'खात्री नाही',
  'chk.status.NOT_APPLICABLE': 'गरज नाही',
  'chk.status.WAIVED_BY_OFFICER': 'क्लेम अधिकाऱ्याने पुढे जाऊ दिले',
  'CHK_COVER_IN_FORCE': 'आपले कवर सुरू होते',
  'CHK_PREMIUM_PREPAID': 'प्रीमियम आधीच भरलेले होते',
  'CHK_COVER_BEFORE_ALERT': 'आपले कवर अलर्टच्या आधी घेतले होते',
  'CHK_ALERT_ACTIVE': 'आपल्या परिसरात हवामान अलर्ट होता',
  'CHK_INDEX_QUORUM': 'आपल्या परिसरात पुरेशी दुकाने मोजली गेली',
  'CHK_BELOW_FLOOR': 'आपल्या परिसरातील विक्री भरपाईच्या पातळीखाली राहिली',
  'CHK_BELOW_MODEL_RANGE': 'घट नेहमीच्या मंद दिवसापेक्षा जास्त होती',
  'CHK_SILENCE_VERIFIED': 'आमच्या नोंदींनुसार आपल्या दुकानात दिवसभर विक्री नाही',
  'CHK_SLIP_READABLE': 'पर्ची स्पष्ट आहे',
  'CHK_NAME_MATCHES_KYC': 'पर्चीवरील नाव आपल्या Paytm खात्याशी जुळते',
  'CHK_DATES_MATCH': 'पर्चीवरील तारखा दुकान बंद असलेल्या दिवसांना व्यापतात',
  'CHK_WITHIN_AUTO_LIMIT': 'दिवसांची संख्या आपोआप भरपाईच्या मर्यादेत आहे',
  'CHK_NOT_ALREADY_PAID': 'या दिवसांची रक्कम आधी दिली गेली नाही',
  'CHK_WITHIN_ANNUAL_LIMIT': 'आपल्या वार्षिक मर्यादेत',
  'CF_TITLE': 'काय बदलले असते तर निकाल बदलला असता',
  'CF_FOOTER': 'हे फक्त या एका निर्णयाचे कारण सांगते. भविष्यातील घटनेचा निर्णय तेव्हा त्याच तपासण्यांनी ठरेल.',
  'grv.step.PAYTM_DISPUTE': 'आमचा क्लेम अधिकारी',
  'grv.step.INSURER_GRO': 'विमा कंपनीचा तक्रार अधिकारी',
  'grv.step.BIMA_BHAROSA': 'IRDAI चे बीमा भरोसा पोर्टल',
  'grv.step.OMBUDSMAN': 'विमा लोकपाल',
  'grv.clock.own': 'आम्ही {sla_hours} तासांत उत्तर देतो.',
  'grv.clock.confirm.insurer': 'उत्तराची वेळ विमा कंपनीशी बोलून निश्चित होईल.',
  'explain.val.days': '{n} दिवस',
  'explain.val.hours': '{n} तास',
  'DISPUTE_ACK': 'ठीक आहे, मी हे आमच्या टीमला पाठवत आहे. 24 तासांत उत्तर मिळेल.',
  'REASON_COVER_IN_FORCE': 'त्या दिवशी आपले कवर सुरू नव्हते.',
  'REASON_PREMIUM_PREPAID': 'त्या दिवसाचे प्रीमियम आधी भरलेले नव्हते.',
  'REASON_SILENCE_VERIFIED': 'आमच्या नोंदींमध्ये त्या दिवशी दुकान दिवसभर बंद दिसली नाही.',
  'REASON_NOT_ALREADY_PAID': 'त्या दिवसाची रक्कम आधीच दिली गेली आहे.',
  'REASON_WITHIN_ANNUAL_LIMIT': 'यामुळे वार्षिक मर्यादा ओलांडली गेली असती.',
  'REASON_COVER_BEFORE_ALERT': 'कवर अलर्ट जाहीर झाल्यानंतर घेतले होते.',
  'REASON_ALERT_ACTIVE': 'त्या वेळी आपल्या परिसरात कोणताही हवामान अलर्ट नव्हता.',
  'REASON_INDEX_QUORUM': 'हिशोबासाठी आपल्या परिसरात पुरेशी दुकाने नव्हती.',
  'REASON_BELOW_FLOOR': 'आपल्या परिसरातील विक्री भरपाईच्या पातळीखाली गेली नाही.',
  'REASON_BELOW_MODEL_RANGE': 'आपल्या परिसरातील विक्री नेहमीच्या श्रेणीच्या आत राहिली.',
  'REASON_OFFICER_PERSONAL': 'पर्चीची तपासणी केल्यानंतर हा दावा मंजूर होऊ शकला नाही.',
  'SLIP_SHEET_TITLE': 'रुग्णालयाची पर्ची पाठवा',
  'SLIP_SHEET_HELP': 'भरतीची पर्ची, डिस्चार्जचा कागद किंवा बिल यांचा एक फोटो घ्या. चांगल्या प्रकाशात घ्या आणि संपूर्ण पान दिसू द्या.',
  'SLIP_NOTICE': 'पर्चीचा फोटो वाचण्यासाठी एखाद्या AI सेवेकडे (Gemini किंवा Sarvam) पाठवला जाऊ शकतो. कृपया नमुना पर्ची पाठवा, खरी नाही.',
  'SLIP_READING': 'पर्ची वाचली जात आहे…',
  'SLIP_PRECHECK_SHOW': 'आम्ही आपली पर्ची वाचली आहे. कृपया पाहा, हे बरोबर आहे का?',
  'SLIP_FIELD_NAME': 'रुग्णाचे नाव',
  'SLIP_FIELD_ADMITTED': 'भरतीची तारीख',
  'SLIP_FIELD_DISCHARGED': 'डिस्चार्जची तारीख',
  'SLIP_FIELD_HOSPITAL': 'रुग्णालय',
  'SLIP_FIELD_NOT_ON_SLIP': 'पर्चीवर नाही',
  'SLIP_NOTE_NO_DISCHARGE': 'पर्चीवर डिस्चार्जची तारीख नाही. आपण अजून रुग्णालयात असाल, तर हे सामान्य आहे.',
  'SLIP_NOTE_NAME_NOT_LATIN': 'नाव इंग्रजी अक्षरांत नाही, म्हणून आमची टीम ते पाहील.',
  'SLIP_CHECK_READABLE_PASS': 'फोटो स्पष्ट वाचता आला',
  'SLIP_CHECK_READABLE_WARN': 'फोटो स्पष्ट नाही',
  'SLIP_CHECK_NAME_PASS': 'नाव पर्चीवर दिसत आहे',
  'SLIP_CHECK_NAME_WARN': 'नाव स्पष्ट दिसत नाही',
  'SLIP_CHECK_DATES_PASS': 'भरतीची तारीख पर्चीवर दिसत आहे',
  'SLIP_CHECK_DATES_WARN': 'भरतीची तारीख स्पष्ट दिसत नाही',
  'SLIP_ACTION_CONFIRM': 'होय, बरोबर आहे',
  'SLIP_ACTION_RETAKE': 'दुसरा फोटो पाठवा',
  'SLIP_ACTION_TEAM': 'आमच्या टीमकडे पाठवा',
  'SLIP_RETAKE_DOCUMENT': 'हे रुग्णालयाचे कागदपत्र वाटत नाही. कृपया भरतीची पर्ची, डिस्चार्जचा कागद किंवा बिल यांचा फोटो पाठवा.',
  'SLIP_RETAKE_CLEAR': 'फोटो स्पष्ट नाही. कृपया चांगल्या प्रकाशात, पर्ची सरळ ठेवून, संपूर्ण पर्ची दिसेल असा फोटो घ्या.',
  'SLIP_RETAKE_NAME': 'रुग्णाचे नाव स्पष्ट दिसत नाही. संपूर्ण नाव दिसेल असा फोटो पाठवा.',
  'SLIP_RETAKE_DATE': 'भरतीची तारीख स्पष्ट दिसत नाही. संपूर्ण तारीख दिसेल असा फोटो पाठवा.',
  'SLIP_NO_READ': 'आत्ता पर्ची वाचता आली नाही. आपण ती आमच्या टीमकडे पाठवू शकता. टीम ती पाहील.',
  'SLIP_PHOTO_LIMIT': 'आपण यापूर्वीही अनेक फोटो पाठवले आहेत. आता हा आमच्या टीमकडे पाठवा.',
  'SLIP_CONSENT_NEEDED': 'पर्ची वाचण्यापूर्वी आम्हाला आपली संमती हवी आहे. ॲप उघडा आणि पर्ची तिथेच पाठवा. ते आधी आपली संमती विचारेल.',
  'slip.err.too_big': 'फोटो खूप मोठा आहे. मर्यादा {max_mb} MB आहे.',
  'slip.err.bad_type': 'कृपया JPG, PNG किंवा WebP फोटो पाठवा.',
  'slip.err.damaged': 'हा फोटो उघडता आला नाही. कृपया दुसरा फोटो निवडा.',
  'slip.working': 'आपला दावा तपासला जात आहे…',
  'sim.slip': 'SIMULATED पर्ची वाचन. डेमो पर्च्यांसाठी ठरलेला निकाल वापरला जातो.',
  'slip.take_photo': 'फोटो घ्या',
  'slip.choose_gallery': 'गॅलरीतून निवडा',
  'slip.cancel': 'रद्द करा',
  'slip.details': 'तपशील',
  'slip.details.provider': 'वाचणारा: {provider}',
  'slip.details.model': 'मॉडेल: {model}',
  'slip.details.reason': 'कारण: {reason}',
  'slip.what_read': 'आम्हाला जे वाचता आले',
  'slip.not_clear': 'स्पष्ट नाही',
  'slip.demo.title': 'डेमो पावत्या',
  'slip.demo.good': 'डेमो पावती वापरा',
  'slip.demo.blurry': 'अस्पष्ट डेमो पावती वापरा',
  'slip.help_row': 'हॉस्पिटलची पावती पाठवा',
  'slip.err.conflict': 'आत्ता पावतीसाठी कोणताही खुला चेक-इन नाही, किंवा दावा आधीच पाठवला गेला आहे.',
  'slip.err.limit': 'अनेक फोटो आधीच पाठवले गेले आहेत. कृपया पावती आमच्या टीमकडे द्या.',
  'grv.title': 'तक्रार आणि पुढचे टप्पे',
  'grv.error.no_decision': 'आपल्या खात्यावर अजून कोणतीही रक्कम किंवा निर्णय नाही, त्यामुळे इथे तक्रार करण्यासारखे काही नाही. आपल्या दाव्यांचा ट्रॅकर परिस्थिती दाखवतो.',
  'grv.error.no_review': 'आपला कोणताही दावा सध्या पुनरावलोकनासाठी थांबलेला नाही.',
  'consent.title': 'माझा डेटा आणि संमती',
  'activity.title': 'काय वापरले',
}
