"""Calibration data (SPEC §17.4, §24.1).

Calibration is generated by scripts/calibrate.py and stored in backend/artifacts/calibration.json.
If missing, sensible defaults are used.
"""

from __future__ import annotations

import json
from pathlib import Path

from chhatri.sim.types import Calibration as CalibrationBase


def load_calibration(data_dir: Path) -> Calibration:
    """Load calibration from backend/artifacts/calibration.json.

    If the file is missing or invalid, return defaults (pre-calibration guesses).
    """
    artifacts_dir = data_dir.parent / "artifacts"
    calib_path = artifacts_dir / "calibration.json"

    if not calib_path.exists():
        return Calibration()

    try:
        with open(calib_path) as f:
            data = json.load(f)

        # Extract fields with defaults
        anil_base = data.get("anil_base_day_paise", 420_000)
        zone_rain_scale = data.get("zone_rain_scale", {"Z3": 1.0, "Z7": 1.0, "Z12": 1.0})
        z9_slow = data.get("z9_slow_depth", 0.39)
        z7_scale = data.get("z7_other_scale", 1.0)
        z7_tune_id = data.get("z7_tune_merchant_id")
        z7_tune_base = data.get("z7_tune_base_day_paise")

        return Calibration(
            anil_base_day_paise=anil_base,
            zone_rain_scale=zone_rain_scale,
            z9_slow_depth=z9_slow,
            z7_other_scale=z7_scale,
            z7_tune_merchant_id=z7_tune_id,
            z7_tune_base_day_paise=z7_tune_base
        )
    except (json.JSONDecodeError, KeyError, TypeError):
        return Calibration()


class Calibration(CalibrationBase):
    """Alias for convenience."""
    pass
